//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACA_CRONOGRAMA_PAGO_ALUMNO
    {
        public string ANO { get; set; }
        public decimal MES { get; set; }
        public string NUM_MODALIDAD { get; set; }
        public decimal ID_PERSONA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string NOMBRE { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal IMPORTE_PAGAR { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
