//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFI_ACTIVO_FIJO
    {
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string MONEDA { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> DEPRECIACION { get; set; }
        public string CENTRO_COSTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string NRO_SERIE { get; set; }
        public string SERIE_GENERADA { get; set; }
        public decimal CANTIDAD { get; set; }
        public string CDG_MARCA { get; set; }
        public string CDG_MODELO { get; set; }
        public string OBSERVACION { get; set; }
        public string METODO_DEPRECIACION { get; set; }
        public string SITUACION { get; set; }
        public string DEPRECIABLE { get; set; }
        public string AJUSTE_INFLACION { get; set; }
        public decimal SECUENCIA { get; set; }
        public Nullable<decimal> MESES_DEPRE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
