//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFI_DEPRECIACION
    {
        public decimal ANO { get; set; }
        public decimal MES { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string NRO_SERIE { get; set; }
        public string SERIE_GENERADA { get; set; }
        public decimal IMPORTE { get; set; }
        public Nullable<decimal> IMP_OTRO { get; set; }
        public string MONEDA { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
