//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALE_VW_PAGO
    {
        public Nullable<System.DateTime> FECHA { get; set; }
        public string MOVIMIENTO { get; set; }
        public string num_comp { get; set; }
        public int num_itm { get; set; }
        public string cdg_bco { get; set; }
        public string BANCO { get; set; }
        public string num_cta { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> imp { get; set; }
        public Nullable<System.DateTime> fec_venc { get; set; }
        public string cdg_tana { get; set; }
        public string cdg_anal { get; set; }
        public string MOTIVO { get; set; }
        public string OBSERVACION { get; set; }
        public string CDG_MON { get; set; }
        public string SOLICITANTE { get; set; }
        public string NUMDOCU { get; set; }
        public string TDOC { get; set; }
    }
}
