//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPMOV_ACCESO_USUARIO
    {
        public string USUARIO { get; set; }
        public string CODIGO { get; set; }
        public string NUEVO { get; set; }
        public string MODIFICAR { get; set; }
        public string ELIMINAR { get; set; }
        public string ANULAR { get; set; }
    }
}
