//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_ALL_COTIZACION_VENTA
    {
        public Nullable<int> ANO { get; set; }
        public Nullable<int> MES { get; set; }
        public decimal VENTA_REAL_NETA_USD { get; set; }
        public string MOTIVO { get; set; }
        public string ESTADO { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string VENDEDOR { get; set; }
        public Nullable<decimal> ANO_CIERRE { get; set; }
        public string MES_CIERRE { get; set; }
        public Nullable<decimal> AL_30 { get; set; }
        public Nullable<decimal> AL_50 { get; set; }
        public Nullable<decimal> AL_80 { get; set; }
    }
}
