//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CITA
    {
        public decimal ID_CITA { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string ESPECIALIDAD { get; set; }
        public System.DateTime FECHA_CITA { get; set; }
        public System.DateTime FECHA_PROGRAMADA { get; set; }
        public string HORARIO { get; set; }
        public string TURNO { get; set; }
        public string DETALLE { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
