//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_HISTORIA_PACIENTE
    {
        public decimal ID_HISTORIA { get; set; }
        public decimal ID_PEDIDO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public Nullable<System.DateTime> FECHA_ATENCION { get; set; }
        public Nullable<decimal> MEDICO { get; set; }
        public string ESPECIALDAD { get; set; }
        public string EXPLORACION_HECHA { get; set; }
        public string DIAGNOSTICO_HECHA { get; set; }
        public string TRATAMIENTO_HECHA { get; set; }
        public string OBSERVACION_HECHA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
