//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_COMISION_FACT
    {
        public decimal ANO { get; set; }
        public decimal MES { get; set; }
        public string VENDEDOR { get; set; }
        public decimal CUOTA { get; set; }
        public Nullable<decimal> VALOR_NETO { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public Nullable<decimal> COBRANZA { get; set; }
        public Nullable<decimal> COMISION_PAGAR { get; set; }
        public string MONEDA { get; set; }
        public decimal POR_CUMPLIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    }
}
