//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_SERVIDOR_BD
    {
        public string RUC { get; set; }
        public string SERVIDOR { get; set; }
        public string BASE_DATO { get; set; }
        public string TIPO_SEGURIDAD { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string RUTA_BASE_DATO { get; set; }
        public string NOM_SERVIDOR { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
