//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_DOCUMENTO
    {
        public string CODIGO_SUCURSAL { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string RUC { get; set; }
        public string DIRECCION { get; set; }
        public string COMENTARIO { get; set; }
        public string REFERENCIA1 { get; set; }
        public string REFERENCIA2 { get; set; }
        public string REFERENCIA3 { get; set; }
        public string REFERENCIA4 { get; set; }
        public string REFERENCIA5 { get; set; }
        public string REFERENCIA6 { get; set; }
        public string REFERENCIA7 { get; set; }
        public string REFERENCIA8 { get; set; }
        public string REFERENCIA9 { get; set; }
        public string REFERENCIA10 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
