//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_SWT_MD
    {
        public string MD { get; set; }
        public string SWT_MD { get; set; }
        public string CNT_MD { get; set; }
        public string US_CR { get; set; }
        public string FC_CR { get; set; }
    }
}
