//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_DISENO_DOCUMENTO
    {
        public string TIPO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NOMBRE_COLUMNA { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int LONGITUD { get; set; }
        public int ORDEN { get; set; }
        public string SALTO_LINEA { get; set; }
        public string ALINEACION { get; set; }
        public string FUENTE { get; set; }
        public string ESTILO { get; set; }
        public string TAMANO { get; set; }
        public Nullable<int> NRO_DECIMAL { get; set; }
    }
}
