//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_SALDOSAG
    {
        public string ano_sld { get; set; }
        public string mes_sld { get; set; }
        public string cdg_cta { get; set; }
        public string cdg_mon { get; set; }
        public string cdg_tana { get; set; }
        public string cdg_anal { get; set; }
        public string cdg_cct { get; set; }
        public decimal deb_sld { get; set; }
        public decimal deb_ofi { get; set; }
        public decimal deb_pat { get; set; }
        public decimal hab_sld { get; set; }
        public decimal hab_ofi { get; set; }
        public decimal hab_pat { get; set; }
        public decimal venta { get; set; }
        public decimal compra { get; set; }
    }
}
