//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_TOPERACION_CIERRE
    {
        public string CODIGO { get; set; }
        public string NUMERO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string OPERACION { get; set; }
        public string CUENTA { get; set; }
        public string CUENTAT { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
