//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_DLINEA_ESFI
    {
        public string swt_ef { get; set; }
        public string cdg_rub { get; set; }
        public string cdg_lin { get; set; }
        public string cdg_cta { get; set; }
        public string des_cta { get; set; }
    }
}
