//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PLAN_CUENTA
    {
        public string conta_codigo { get; set; }
        public string conta_descripcion { get; set; }
        public string conta_movimiento { get; set; }
        public string conta_monetaria { get; set; }
        public string conta_centro_costo { get; set; }
        public string conta_oficial { get; set; }
        public string conta_patrimonial { get; set; }
        public string conta_deudora { get; set; }
        public string conta_acrededora { get; set; }
        public string conta_tipo_analitica { get; set; }
        public string conta_cta_debe { get; set; }
        public string conta_cta_haber { get; set; }
        public string usuario_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string conta_estado { get; set; }
        public string conta_cambio { get; set; }
        public string conta_ganancia { get; set; }
        public string conta_perdida { get; set; }
        public string conta_nivel_cuenta { get; set; }
        public string conta_tipo_cuenta { get; set; }
        public string conta_tipo_analisis { get; set; }
        public string conta_cta_cte { get; set; }
        public string conta_prc_gst { get; set; }
        public string conta_cta_flujo { get; set; }
        public string conta_cta_cierre { get; set; }
        public string conta_moneda { get; set; }
        public string conta_codigo_parent { get; set; }
        public string conta_codigo_eq { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string conta_monetaria_especial { get; set; }
    }
}
