//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_DETALLE_PRESUPUESTO
    {
        public string NUM_PRE { get; set; }
        public string NUM_CTA { get; set; }
        public string ANO { get; set; }
        public string MES { get; set; }
        public string CDG_METO { get; set; }
        public Nullable<decimal> DEBITO { get; set; }
        public Nullable<decimal> CREDITO { get; set; }
        public Nullable<decimal> DEBITO_R { get; set; }
        public Nullable<decimal> CREDITO_R { get; set; }
        public Nullable<decimal> DEBITO_D { get; set; }
        public Nullable<decimal> CREDITO_D { get; set; }
        public Nullable<decimal> DEBITO_R_D { get; set; }
        public Nullable<decimal> CREDITO_R_D { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
