//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAVW_LIBRO_MAYOR
    {
        public string CDG_CTA { get; set; }
        public string ANO_VOUC { get; set; }
        public string MES_VOUC { get; set; }
        public string NUM_VOUC { get; set; }
        public string CDG_TAS { get; set; }
        public string NUM_REG { get; set; }
        public Nullable<System.DateTime> FEC_VOUC { get; set; }
        public Nullable<System.DateTime> FEC_DOCU { get; set; }
        public string GLS_VOUC { get; set; }
        public string CDG_LIBRO { get; set; }
        public string CORRELATIVO { get; set; }
        public string NUM_DOCU { get; set; }
        public string CONTA_CODIGO { get; set; }
        public string CONTA_DESCRIPCION { get; set; }
        public Nullable<decimal> DEB_NAC { get; set; }
        public Nullable<decimal> HAB_NAC { get; set; }
        public string CDG_TOPE { get; set; }
        public string NUM_REG2 { get; set; }
        public string CDG_TAS2 { get; set; }
        public string SWT_OFI { get; set; }
        public string SWT_PAT { get; set; }
        public string CDG_CCT { get; set; }
        public string CDG_MON { get; set; }
        public Nullable<System.DateTime> VCT_DOCU { get; set; }
        public string CDG_TDOC { get; set; }
    }
}
