//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PROD_CTA
    {
        public string tipo_producto { get; set; }
        public string CATEGORIA { get; set; }
        public string cuenta_existencia { get; set; }
        public string cuenta_recibir { get; set; }
        public string cuenta_venta { get; set; }
        public string cuenta_costo_venta { get; set; }
        public string cuenta_compra { get; set; }
        public string cuenta_ingr_producto { get; set; }
        public string cuenta_proc_producto { get; set; }
        public string cuenta_vta_diferida { get; set; }
        public string cuenta_dev_vta { get; set; }
        public string cuenta_var_exi { get; set; }
        public string cuenta_dev_compra { get; set; }
        public string cuenta_sal_of { get; set; }
        public string cuenta_dev_of { get; set; }
        public string cuenta_sal_con { get; set; }
        public string cuenta_dev_con { get; set; }
        public string cuenta_puente { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    }
}
