//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_RUBRO_ESFI
    {
        public string swt_ef { get; set; }
        public string cdg_rub { get; set; }
        public string des_rub { get; set; }
        public string swt_rub { get; set; }
        public string swt_ap { get; set; }
        public string swt_fn { get; set; }
        public string ftr_rub { get; set; }
        public string ord_rub { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    }
}
