//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PRODUCTO
    {
        public string CODIGO_EMPRESA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string CODIGO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION_EXTENDIDA { get; set; }
        public string ID_UNIDAD { get; set; }
        public string ID_CATEGORIA { get; set; }
        public string ID_GRUPO { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
    }
}
