//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SEGUIMIENTO
    {
        public string CODIGO_CAMPANA { get; set; }
        public decimal ID_SEGUIMIENTO { get; set; }
        public Nullable<decimal> ID_CLIENTE_CAMPANA { get; set; }
        public string SITUACION { get; set; }
        public string USUARIO { get; set; }
        public string USUARIO_PARA { get; set; }
        public string PRIORIDAD { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public string HORA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public string HORA_FIN { get; set; }
        public string LUGAR { get; set; }
        public string TIPO { get; set; }
        public string PROCEDENCIA { get; set; }
        public string TIPO_SOLUCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string SOLUCION { get; set; }
        public string REF1 { get; set; }
        public string TIPO_EVENTO { get; set; }
        public string USUARIO_FINALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_FINALIZACION { get; set; }
        public string HORA_FINALIZACION { get; set; }
        public string USUARIO_REF1 { get; set; }
        public Nullable<System.DateTime> FECHA_REF1 { get; set; }
        public string HORA_REF1 { get; set; }
        public string NOTA { get; set; }
        public string ETAPA_VENTA { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> IMPORTE_ESTIMADO { get; set; }
        public Nullable<decimal> MES_CIERRE { get; set; }
        public Nullable<decimal> ANO_CIERRE { get; set; }
        public Nullable<decimal> ID_MAIN_PARENT { get; set; }
        public Nullable<decimal> ID_PARENT { get; set; }
        public string MOTIVO_PERDIDA { get; set; }
        public string COMPETENCIA { get; set; }
        public string NOTA_PERDIDA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public string ASUNTO { get; set; }
        public string SITIO { get; set; }
        public string TECNICO { get; set; }
        public string SUCURSAL { get; set; }
        public string NUM_COR { get; set; }
        public string ESTADO { get; set; }
    }
}
