//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FE_DETALLE_RESUMEN_BAJA
    {
        public string CODIGO_EMPRESA { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
        public decimal NUM_ITEM { get; set; }
        public string TDOC { get; set; }
        public string SERIE { get; set; }
        public decimal CORRELATIVO { get; set; }
        public string NUMDOC { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<decimal> ID_DOCUMENTO { get; set; }
    }
}
