//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FE_RESUMEN_BAJA
    {
        public string CODIGO_EMPRESA { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string ESTADO { get; set; }
        public string EST_REG { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public string USUARIO_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
    }
}
