//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_DATA_REQUISICIONES
    {
        public string NUM_GASTO { get; set; }
        public string TIPO_CONCEPTO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ANO { get; set; }
        public string MES { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string CATEGORIA { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string PERSONA { get; set; }
        public string CONCEPTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UNIDAD { get; set; }
        public string MONEDA { get; set; }
        public string AFECTO { get; set; }
        public string INCLUYE_IGV { get; set; }
        public Nullable<decimal> PRECIO_SOLES { get; set; }
        public Nullable<decimal> SUBTOTAL_SOLES { get; set; }
        public Nullable<decimal> IGV_SOLES { get; set; }
        public Nullable<decimal> IMP_SOLES { get; set; }
        public Nullable<decimal> PRECIO_DOLAR { get; set; }
        public Nullable<decimal> SUBTOTAL_DOLAR { get; set; }
        public Nullable<decimal> IGV_DOLAR { get; set; }
        public Nullable<decimal> IMP_DOLAR { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> IMES { get; set; }
        public string ESTADO_PAGO { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> TOTAL_DOLAR { get; set; }
        public Nullable<decimal> TOTAL_SOLES { get; set; }
        public Nullable<decimal> STOTAL_DOLAR { get; set; }
        public Nullable<decimal> STOTAL_SOLES { get; set; }
        public decimal ID_PRODUCTO { get; set; }
    }
}
