//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_CAMBIO_CAMPOS
    {
        public string TABLA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string RUC { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_ITEM { get; set; }
        public string CAMPO { get; set; }
        public string REFERENCIA1 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
