//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CONTROL_GARANTIA
    {
        public string NOMBRE { get; set; }
        public string SERIE { get; set; }
        public string SERIE_REEM { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int RECORDATORIO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public Nullable<int> ID_GUIA { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string NOTA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
