//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_LIBBCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_LIBBCO()
        {
            this.OPE_DETALLE_LIBBCO = new HashSet<OPE_DETALLE_LIBBCO>();
        }
    
        public short ANO { get; set; }
        public short MES { get; set; }
        public string CDG_BCO { get; set; }
        public string NUM_CTA { get; set; }
        public string NUM_COR { get; set; }
        public string CDG_MON { get; set; }
        public System.DateTime FEC_DOCU { get; set; }
        public string NUM_DOCU { get; set; }
        public string CON_DOCU { get; set; }
        public decimal IMP_DEBE { get; set; }
        public decimal IMP_HABER { get; set; }
        public decimal IMP_SALDO { get; set; }
        public string CDG_TMOV { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public string CDG_CTA { get; set; }
        public string SWT_EST { get; set; }
        public string SWT_ATN { get; set; }
        public Nullable<decimal> TIP_CMB { get; set; }
        public string DES_PRV { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string NUM_COR_MODULO { get; set; }
        public string MODULO { get; set; }
        public string FECHA_REF1 { get; set; }
        public string CDG_BCO2 { get; set; }
        public string NUM_CTA2 { get; set; }
        public string SWT_PRO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public Nullable<decimal> AVANCE { get; set; }
        public string TURNO { get; set; }
        public string NUM_REQUI { get; set; }
        public string NUM_REF { get; set; }
        public Nullable<decimal> ID_SD { get; set; }
        public string DOCS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_LIBBCO> OPE_DETALLE_LIBBCO { get; set; }
    }
}
