//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PROGRAMACION_PAGO
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string NUM { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> IMPORTE_MN { get; set; }
        public Nullable<decimal> IMPORTE_ME { get; set; }
        public string CDG_BANCO { get; set; }
        public string NUM_CTA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
