//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DIST_GAST_IMPORTACION
    {
        public string ci_codigo { get; set; }
        public string tipo_documento { get; set; }
        public string numero_documento { get; set; }
        public string ruc_prov { get; set; }
        public string base_prorrateo { get; set; }
        public decimal valor { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string ci_codigo2 { get; set; }
        public string tipo_documento_o { get; set; }
        public string numero_documento_o { get; set; }
        public string ruc_prov_o { get; set; }
        public string CDG_COSTEO { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<int> secuencia_docu { get; set; }
    }
}
