//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CREQUERIMIENTO
    {
        public string CODIGO_REQUERIMIENTO { get; set; }
        public string TIPO_REQUERIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public string ENTREGADO { get; set; }
        public string PRIORIDAD { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public string HORA_SOLICITUD { get; set; }
        public string SOLICITADO_POR { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string MANAGER { get; set; }
        public string SUPERVISOR { get; set; }
        public string SITE { get; set; }
        public string NOMBRE_SITE { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<System.DateTime> FECHA_REQUERIDA { get; set; }
        public string HORA_REQUERIDA { get; set; }
        public string TRANSPORTE { get; set; }
        public string AGENCIA_TRANSPORTE { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string NOMBRE_CONTACTO1 { get; set; }
        public string DNI_CONTACTO1 { get; set; }
        public string TELEFONO_CONTACTO1 { get; set; }
        public string NOMBRE_CONTACTO2 { get; set; }
        public string DNI_CONTACTO2 { get; set; }
        public string TELEFONO_CONTACTO2 { get; set; }
        public string TIPO_TRANSPORTE { get; set; }
        public string SWT_REQ { get; set; }
        public string ALMACEN { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_ATENDIDO { get; set; }
        public string HORA_ATENDIDO { get; set; }
        public Nullable<System.DateTime> FECHA_PROGRAMADA { get; set; }
        public string HORA_PROGRAMADA { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSITO { get; set; }
        public string HORA_TRANSITO { get; set; }
        public Nullable<System.DateTime> FECHA_AGENCIA { get; set; }
        public string HORA_AGENCIA { get; set; }
        public string NODO_DESPACHO { get; set; }
        public string CDG_CECO { get; set; }
        public Nullable<System.DateTime> FECHA_PROGRAMA_ALMACEN { get; set; }
        public string USUARIO_PROGRAMA_ALMACEN { get; set; }
        public Nullable<decimal> ID_REQ { get; set; }
    }
}
