//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_DOCUMENTO_COMPRA2
    {
        public int ID_DOCUMENTO { get; set; }
        public string RUC_PRV { get; set; }
        public string NUM_DOCU { get; set; }
        public string CDG_TDOC { get; set; }
        public Nullable<int> ID_OC { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public string DESCRIPCION_PROD { get; set; }
        public Nullable<decimal> CAN_DFAC { get; set; }
        public Nullable<decimal> PRE_DFAC { get; set; }
        public Nullable<decimal> DCT_DFAC { get; set; }
        public Nullable<decimal> IMP_DFAC { get; set; }
        public string CUENTA { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string AFINA { get; set; }
        public string CDG_TANA { get; set; }
        public string CDG_ANAL { get; set; }
        public string TIP_PROV { get; set; }
        public string NUM_POLI { get; set; }
        public string BAS_POR { get; set; }
        public string EST_POLI { get; set; }
        public decimal NUM_SEC { get; set; }
        public string ORD_PROD { get; set; }
        public string ORD_SERV { get; set; }
        public Nullable<decimal> VAL_VALOR { get; set; }
        public string CDG_PROD { get; set; }
        public string CDG_CC { get; set; }
        public string CDG_GASTO { get; set; }
        public string CDG_UNIDAD { get; set; }
        public Nullable<decimal> ID_GUIA { get; set; }
        public string PRECIO_IGV { get; set; }
        public string CODIGO_ALMACEN { get; set; }
        public string SCDG_CC { get; set; }
        public Nullable<decimal> PRECIO_AJUSTE { get; set; }
        public Nullable<decimal> IMPORTE_AJUSTE { get; set; }
        public Nullable<decimal> PRECIO_OTRO { get; set; }
        public Nullable<decimal> IMPORTE_OTRO { get; set; }
        public Nullable<decimal> ITEM_PF { get; set; }
        public Nullable<decimal> PRE_SIGV { get; set; }
        public Nullable<decimal> PRE_INV { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
    }
}
