//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_COTIZACION
    {
        public decimal ID_COTIZACION { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public decimal IMPORTE { get; set; }
        public string OBSERVACION { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal PRECIO_ORIGINAL { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> IMPORTE_DSCTO { get; set; }
        public string AFECTO_IGV { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public Nullable<decimal> ID_PRESUPUESTO { get; set; }
        public string CDG_SERV { get; set; }
        public byte[] IMAGEN_REF { get; set; }
        public string OBSERVACION2 { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> POR_PERCEPCION { get; set; }
        public Nullable<decimal> PERCEPCION { get; set; }
        public Nullable<decimal> VALOR_VEN { get; set; }
        public string UNID_VEN { get; set; }
        public Nullable<System.DateTime> FECHA_VEN { get; set; }
        public string CDG_KIT { get; set; }
        public string SWT_PIGV { get; set; }
        public Nullable<decimal> POR_DETRACCION { get; set; }
        public Nullable<decimal> DETRACCION { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
        public Nullable<decimal> MARGEN { get; set; }
        public Nullable<decimal> IMPORTE_MARGEN { get; set; }
        public Nullable<decimal> COSTO_ADIC { get; set; }
        public Nullable<decimal> CANT_KIT { get; set; }
        public string SWT_IMP { get; set; }
        public string TIPO_ITEM { get; set; }
    
        public virtual OPE_COTIZACION_VENTA OPE_COTIZACION_VENTA { get; set; }
    }
}
