//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PRESUPUESTO2
    {
        public decimal ID_PRESUPUESTO { get; set; }
        public string CODIGO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public string ID_REQUERIMIENTO { get; set; }
        public string CATEGORIA { get; set; }
        public string SERVICIO { get; set; }
        public string CDG_ING { get; set; }
        public string MONEDA { get; set; }
        public decimal ID_PARENT { get; set; }
        public string ESTADO { get; set; }
        public decimal COSTO { get; set; }
        public decimal VALOR_VENTA { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public string OBSERVACION { get; set; }
        public string OBSERVACION2 { get; set; }
        public string SWT_MAIN { get; set; }
        public int CANTIDAD { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<decimal> GASTO_ADMINISTRATIVO { get; set; }
        public Nullable<decimal> GASTO_GENERAL { get; set; }
        public Nullable<decimal> MARGEN { get; set; }
        public Nullable<decimal> IMPORTE_ADMINISTRATIVO { get; set; }
        public Nullable<decimal> IMPORTE_GENERAL { get; set; }
        public Nullable<decimal> IMPORTE_MARGEN { get; set; }
    }
}
