//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_TRANSFERENCIA
    {
        public string NUM_TRAN { get; set; }
        public System.DateTime FEC_TRAN { get; set; }
        public string RUC_PRV { get; set; }
        public string CDG_BCO { get; set; }
        public string NUM_CTA { get; set; }
        public string CDG_CTA { get; set; }
        public string CDG_MON { get; set; }
        public string NUM_COR { get; set; }
        public string NUM_CHEQ { get; set; }
        public decimal IMP_TRAN { get; set; }
        public string BCO_TRAN { get; set; }
        public string CTA_TRAN { get; set; }
        public string MON_TRAN { get; set; }
        public string OBS_TRAN { get; set; }
        public decimal PAG_TRAN { get; set; }
        public string SWT_TRAN { get; set; }
        public string CDG_TDOC { get; set; }
        public string CDG_TMOV { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string REF_NUMERO { get; set; }
        public string REF_CDG_TDOC { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string NUM_REQUI { get; set; }
        public string SWT_REQ { get; set; }
        public string REFERENCIA { get; set; }
    }
}
