//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_PRESUPUESTO
    {
        public decimal ID_PRESUPUESTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string CDG_SERV { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal COSTO { get; set; }
        public decimal MARGEN { get; set; }
        public decimal DSCTO { get; set; }
        public decimal VALOR_UNIT { get; set; }
        public string OBSERVACION { get; set; }
        public string OBSERVACION2 { get; set; }
        public string TIPO { get; set; }
        public int SECUENCIA { get; set; }
        public string MONEDA { get; set; }
        public decimal VALOR_ORI { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> IMPORTE2 { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<decimal> ID_TITULO { get; set; }
        public Nullable<decimal> SEC_OH { get; set; }
        public string ORDEN_HOJA { get; set; }
        public Nullable<decimal> ID_PRODUCTO2 { get; set; }
        public string CDG_TEMP { get; set; }
        public string NOM_TEMP { get; set; }
        public string DESC_TEMP { get; set; }
        public string UND_TEMP { get; set; }
        public Nullable<decimal> REND_TEMP { get; set; }
        public Nullable<decimal> JORN_TEMP { get; set; }
        public Nullable<decimal> PCON_TEMP { get; set; }
        public Nullable<decimal> ICON_TEMP { get; set; }
        public Nullable<decimal> TOTAL_TEMP { get; set; }
        public Nullable<int> SEC_PRES { get; set; }
        public Nullable<int> SEC_ORD { get; set; }
    
        public virtual OPE_PRESUPUESTO OPE_PRESUPUESTO { get; set; }
    }
}
