//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DOCUMENTO_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_DOCUMENTO_VENTA()
        {
            this.OPE_DETALLE_DOCUMENTO_VENTA = new HashSet<OPE_DETALLE_DOCUMENTO_VENTA>();
        }
    
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string HORA { get; set; }
        public int ID_PERSONA { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string TIPO_VENTA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string MONEDA { get; set; }
        public decimal POR_IGV { get; set; }
        public decimal IGV { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public decimal EFECTIVO { get; set; }
        public decimal ABONO { get; set; }
        public decimal VUELTO { get; set; }
        public string ESTADO { get; set; }
        public string NUMERO_MAQUINA { get; set; }
        public string MOZO { get; set; }
        public string TURNO { get; set; }
        public string CODIGO_CAJERO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<decimal> VISA { get; set; }
        public Nullable<decimal> MASTERCARD { get; set; }
        public Nullable<decimal> RIPLEY { get; set; }
        public Nullable<decimal> SAGA { get; set; }
        public Nullable<decimal> OTROS { get; set; }
        public string NUMERO_COMANDA { get; set; }
        public string RUC { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string DIRECCION_PERSONA { get; set; }
        public Nullable<decimal> COMISION_VISA { get; set; }
        public Nullable<decimal> COMISION_MASTERCARD { get; set; }
        public Nullable<decimal> COMISION_RIPLEY { get; set; }
        public Nullable<decimal> COMISION_SAGA { get; set; }
        public Nullable<decimal> COMISION_OTROS { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> ID_PEDIDO { get; set; }
        public Nullable<decimal> ID_DOCUMENTO2 { get; set; }
        public string TIPO_DOCUMENTO2 { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_REFERENCIA { get; set; }
        public Nullable<System.DateTime> FEC_VCTO { get; set; }
        public Nullable<System.DateTime> FEC_CANC { get; set; }
        public string DOC_REF { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public Nullable<decimal> TOT_COB { get; set; }
        public Nullable<decimal> VAL_FPAG { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string REDONDEO { get; set; }
        public string ANTICIPO { get; set; }
        public Nullable<decimal> ID_GUIA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<decimal> VAL_ANTICIPO { get; set; }
        public Nullable<decimal> VAL_PERCEPCION { get; set; }
        public string REF_ZONAS { get; set; }
        public Nullable<decimal> ID_CHECKINOUT { get; set; }
        public Nullable<decimal> ID_COTIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public Nullable<decimal> CANT_DECIMAL { get; set; }
        public Nullable<System.DateTime> FECHA_APERTURA { get; set; }
        public string NOM_IMP { get; set; }
        public Nullable<decimal> PROPINA { get; set; }
        public string CAJA { get; set; }
        public string SWT_CUO { get; set; }
        public string VALOR_RESUMEN { get; set; }
        public string TEXTO_IMPORTE { get; set; }
        public string VALOR_FIRMA { get; set; }
        public string M_ERROR { get; set; }
        public string M_EXITO { get; set; }
        public Nullable<decimal> M_CONTINGENCIA { get; set; }
        public string USUARIO_CONTINGENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_CONTINGENCIA { get; set; }
        public string REFE_CORR { get; set; }
        public Nullable<decimal> IMP_OPERACION_GRAVADA { get; set; }
        public Nullable<decimal> IMP_OPERACION_INAFECTA { get; set; }
        public Nullable<decimal> IMP_OPERACION_EXONERADA { get; set; }
        public Nullable<decimal> IMP_OPERACION_EXPORTACION { get; set; }
        public string REFLETRA { get; set; }
        public string SWT_CC { get; set; }
        public string USUARIO_CAJA { get; set; }
        public string SWT_CANJE { get; set; }
        public Nullable<decimal> ICBPER { get; set; }
        public Nullable<bool> FLAG_ERROR { get; set; }
        public Nullable<bool> FLAG_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public string USUARIO_ENVIO { get; set; }
        public string SWT_FE { get; set; }
        public string SWT_BJ { get; set; }
        public string SWT_GN { get; set; }
        public string STR_MOT { get; set; }
        public string DNI { get; set; }
        public string NOMBRE_APELLIDO { get; set; }
        public string TEL_CELULAR { get; set; }
        public string CDG_CECO { get; set; }
        public string CDG_SCECO { get; set; }
        public Nullable<decimal> PTOS_VTA { get; set; }
        public Nullable<decimal> DSCTO_PTOS_VTA { get; set; }
        public Nullable<decimal> PTOS_VTA_APLICA { get; set; }
        public string TIPO_OPERACION { get; set; }
        public Nullable<decimal> IMP_RED { get; set; }
        public string NUM_PLACA { get; set; }
        public Nullable<decimal> IMP_CREDITO { get; set; }
        public string FECHA_INGRESO { get; set; }
        public string FECHA_SALIDA { get; set; }
        public string TEXTO_CONTRATO { get; set; }
        public string TEXTO_CONTRATO2 { get; set; }
        public Nullable<decimal> MINUTOS { get; set; }
        public Nullable<decimal> HORAS { get; set; }
        public Nullable<decimal> MINUTOSE { get; set; }
        public Nullable<decimal> HORASE { get; set; }
        public Nullable<decimal> MINUTOSST { get; set; }
        public Nullable<decimal> HORASST { get; set; }
        public Nullable<decimal> TARIFA { get; set; }
        public Nullable<decimal> CANT_HS { get; set; }
        public Nullable<decimal> TARIFA_PLANA { get; set; }
        public Nullable<decimal> ID_CONTRATO { get; set; }
        public string NOM_DELIVERY { get; set; }
        public Nullable<decimal> POR_RETENCION { get; set; }
        public Nullable<decimal> IMP_RETENCION { get; set; }
        public Nullable<decimal> POR_RETENCION_OTRO { get; set; }
        public Nullable<decimal> IMP_RETENCION_OTRO { get; set; }
        public Nullable<decimal> ID_MEDICO { get; set; }
        public string CDG_ESPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_DOCUMENTO_VENTA> OPE_DETALLE_DOCUMENTO_VENTA { get; set; }
    }
}
