//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_PLANTILLA_RECETA
    {
        public string CODIGO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal COSTO_UNITARIO { get; set; }
        public int SECUENCIA { get; set; }
        public string TIPO { get; set; }
        public string LISTA_PRECIO { get; set; }
        public Nullable<decimal> PRECIO_LISTA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string IMPRIME { get; set; }
        public string UNIDAD { get; set; }
    }
}
