//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_LETRA_PROVEEDOR
    {
        public string CODIGO_EMPRESA { get; set; }
        public int ID_DOCUMENTO { get; set; }
        public string NUMERO_CANJE { get; set; }
        public int ID_PERSONA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public decimal IMPORTE { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_CANJE { get; set; }
        public Nullable<System.DateTime> FECHA_ANULACION { get; set; }
        public string ESTADO_CANJE { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public string MONEDA { get; set; }
        public decimal IMPORTE_SOLES { get; set; }
        public decimal IMPORTE_DOLAR { get; set; }
        public string MONEDA_CANJE { get; set; }
        public string RUC_DOC { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string NUM_ORIG_A { get; set; }
        public string NUM_VOUC_A { get; set; }
    }
}
