//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_ASIGNACION_ACTIVO_FIJO
    {
        public int ID_ASIGNACION { get; set; }
        public decimal daf_id { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
    
        public virtual OPE_DETALLE_ACTIVO_FIJO OPE_DETALLE_ACTIVO_FIJO { get; set; }
    }
}
