//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PEDIDO_PAGO_IHOY
    {
        public decimal ID_PEDIDO { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal MONTO_PAGO_INICIAL_HOY { get; set; }
        public string BANCO_TARJETA_PAGO_INICIAL_HOY { get; set; }
        public string REFERENCIA_PAGO_INICIAL_HOY { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_INICIAL_HOY { get; set; }
        public string FORMA_PAGO_INICIAL_HOY { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
