//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_REQUISICION
    {
        public string CODIGO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CDG_GASTO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal IMPORTE { get; set; }
        public string OBSERVACION { get; set; }
        public string AFECTO_IGV { get; set; }
        public string AI { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
    }
}
