//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_LIQUIDACIONM
    {
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal VALOR_UNITARIO { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UNIDAD { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal VALOR_UNITRARIO_TOTAL { get; set; }
        public string SWT_FACT { get; set; }
    }
}
