//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_VALORIZACION
    {
        public decimal ID_PRODUCTO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public decimal ano { get; set; }
        public decimal mes { get; set; }
        public decimal costo_sol { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<decimal> costo_dol { get; set; }
    }
}
