//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_MESA
    {
        public string PISO { get; set; }
        public int ID_MESA { get; set; }
        public string ESTADO { get; set; }
        public string ESTADO_TRANS { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> SECUENCIA { get; set; }
    }
}
