//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLECC
    {
        public string CODIGO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public int SECUENCIA { get; set; }
        public string AFECTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string OBSERVACION { get; set; }
        public string AFINA { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
        public string SWT_COM { get; set; }
        public Nullable<int> SEC_P { get; set; }
        public string CODIGO_P { get; set; }
        public string CDG_CECO { get; set; }
        public string CDG_SCECO { get; set; }
        public Nullable<decimal> ID_REQ { get; set; }
    }
}
