//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_AZFILACOLUMNAPROD
    {
        public string CODIGO_SUCURSAL { get; set; }
        public string CODIGO_ZONA { get; set; }
        public string FILA { get; set; }
        public string COLUMNA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
