//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_TARIFA
    {
        public decimal ID_TARIFA { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public string AL { get; set; }
        public string AD { get; set; }
        public string MP { get; set; }
        public string PC { get; set; }
        public string TI { get; set; }
        public string CARGO_PERSONA { get; set; }
        public string CARGO_DIA { get; set; }
        public decimal NOCHES { get; set; }
        public decimal ADULTO_MIN { get; set; }
        public decimal ADULTO_MAX { get; set; }
        public decimal NINO_MAX { get; set; }
        public decimal PAX_MIN { get; set; }
        public decimal PAX_MAX { get; set; }
        public decimal NOCHE_MAX { get; set; }
        public decimal NOCHE_MIN { get; set; }
        public decimal DIAS_DSCTO { get; set; }
        public decimal DSCTO { get; set; }
        public string LUNES { get; set; }
        public string MARTES { get; set; }
        public string MIERCOLES { get; set; }
        public string JUEVES { get; set; }
        public string VIERNES { get; set; }
        public string SABADO { get; set; }
        public string DOMINGO { get; set; }
        public string CONCEPTO_CARGO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
