//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PLAN_FACTURACION_OC
    {
        public decimal ID_OC { get; set; }
        public decimal ITEM { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string TIPO { get; set; }
        public decimal VALOR { get; set; }
        public System.DateTime FECHA_ESTIMADA { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
    }
}
