//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SOLICITUD_REQUERIMIENTO
    {
        public decimal ID_REQUERIMIENTO { get; set; }
        public string TIPO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string SOLICITANTE { get; set; }
        public string OBSERVACION { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> ID_PROYECTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
    }
}
