//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_RESULTADO_FINAL_LAB
    {
        public decimal SECUENCIADOC { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal SECUENCIARESUL { get; set; }
        public string CDG_AGRUPACION { get; set; }
        public string TIPO_DATO { get; set; }
        public string VALOR_DEFECTO { get; set; }
        public string NOM_CAMPO { get; set; }
        public string VALOR_OPCION { get; set; }
        public string UNIDAD_VALOR { get; set; }
        public string VALOR_RANGO { get; set; }
        public string VALOR_REFRENCIA { get; set; }
        public string METODO { get; set; }
        public string CDG_REALIZADO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFCACION { get; set; }
    }
}
