//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_MOVBCO_REQ
    {
        public decimal ID_MOVIMIENTO { get; set; }
        public string CODIGO { get; set; }
        public string CDG_BCO_EMP { get; set; }
        public string CTA_CTE_EMP { get; set; }
        public Nullable<System.DateTime> FECH_MOV_BCO { get; set; }
        public string NUM_REF { get; set; }
        public Nullable<decimal> IMP_BCO { get; set; }
        public string DOCS { get; set; }
        public string GIRADO { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string TIPO { get; set; }
        public string DOCS2 { get; set; }
        public string CMITF { get; set; }
        public string DETRACCION { get; set; }
    }
}
