//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DOCUMENTO_VENTA_CONTRATO
    {
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_CONTRATO { get; set; }
        public decimal ANO { get; set; }
        public decimal MES { get; set; }
        public decimal CUOTA { get; set; }
    }
}
