//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_REQITEMS
    {
        public decimal ID_REQUERIMIENTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACION { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
        public string CDG_RESPONSABLE { get; set; }
        public string CDG_USO { get; set; }
        public string CDG_PRIORIDAD { get; set; }
        public string CDG_CUSO { get; set; }
    }
}
