//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_DOCUMENTO_COMPRA
    {
        public decimal ID_DETALLLE { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> IGV_PORCENTAJE { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> DESCUENTO_PORCENTAJE { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public string DESCRIPCION_EXTENDIDA { get; set; }
        public string ID_SUCURSAL { get; set; }
        public int SECUENCIA { get; set; }
        public Nullable<decimal> CANTIDAD_INOUT { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string CODIGO_UNIDAD { get; set; }
        public Nullable<decimal> COSTOF { get; set; }
        public Nullable<decimal> COSTOL { get; set; }
        public string CDG_PROD { get; set; }
        public Nullable<decimal> COSTOD { get; set; }
        public Nullable<decimal> PRECIO_COMPRAD { get; set; }
        public string UNIDAD_EQUI { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public Nullable<int> SEC_REQ { get; set; }
        public string REQ { get; set; }
        public Nullable<decimal> ID_OC { get; set; }
        public string COMENTARIO { get; set; }
        public string SWT_IMP { get; set; }
        public Nullable<decimal> ID_RECETA { get; set; }
        public Nullable<decimal> SEC_RECETA { get; set; }
        public string CDG_CC { get; set; }
        public string SCDG_CC { get; set; }
        public string CDG_ZONA { get; set; }
        public string FILA { get; set; }
        public string COLUMNA { get; set; }
    
        public virtual OPE_DOCUMENTO_COMPRA OPE_DOCUMENTO_COMPRA { get; set; }
        public virtual OPE_PRODUCTO OPE_PRODUCTO { get; set; }
    }
}
