//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DSCTO_CANTIDAD_PRODUCTO
    {
        public string CDG_LISTA_PRECIO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal DSCTO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal PRECIO_DSCTO { get; set; }
        public string MONEDA { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal SECUENCIA { get; set; }
        public string TIPO { get; set; }
        public string AUTO_P { get; set; }
        public string UNIDAD { get; set; }
        public decimal FACTOR_CONVERSION { get; set; }
    }
}
