//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COSTO_PROM
    {
        public string CODIGO_SUCURSAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int MES { get; set; }
        public int ANO { get; set; }
        public decimal COSTO { get; set; }
        public decimal SALDO { get; set; }
        public Nullable<decimal> COSTOF { get; set; }
        public Nullable<decimal> COSTOL { get; set; }
    }
}
