//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_MOVIMIENTO_DINERO
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL_ORIGEN { get; set; }
        public string CODIGO_SUCURSAL_DESTINO { get; set; }
        public string ES_TRASLADO { get; set; }
        public string TIPO_MOV { get; set; }
        public decimal ID_MOVIMIENTO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string CDG_CONCEPTO { get; set; }
        public string CONCEPTO { get; set; }
        public string TIPO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO { get; set; }
        public string MONEDA { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public decimal IMPORTE { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TURNO { get; set; }
        public string ALMACEN { get; set; }
        public string COBRADOR { get; set; }
        public string CAJERO { get; set; }
        public Nullable<System.DateTime> FECHA_APERTURA { get; set; }
    }
}
