//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_GUIA3
    {
        public decimal ID_PRODUCTO { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string CDG_UNIDAD { get; set; }
        public decimal FACTOR { get; set; }
        public string CDG_UNIDAD_EQUI { get; set; }
        public decimal CANTIDAD { get; set; }
        public string CDG_CAJA { get; set; }
        public string CDG_COLUMNA { get; set; }
        public string CDG_CASILLERO { get; set; }
        public string CDG_MARCA { get; set; }
        public string CDG_MODELO { get; set; }
        public Nullable<decimal> SECUENCIA { get; set; }
    }
}
