//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_REPROGRAMACION_OC
    {
        public decimal ID_OC { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public int SEC_OC { get; set; }
        public decimal SECUENCIA { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string TIPO_FECHA { get; set; }
        public string ESTADO { get; set; }
        public string CANAL { get; set; }
    }
}
