//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_ENTRE
    {
        public string CDG_TIAN { get; set; }
        public string CDG_ANAL { get; set; }
        public string NUM_CAJA { get; set; }
        public string NUM_COR { get; set; }
        public string CDG_MCJA { get; set; }
        public System.DateTime FEC_DCJA { get; set; }
        public string DOC_DCJA { get; set; }
        public string CNC_DCJA { get; set; }
        public Nullable<decimal> IMP_DCJA { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string RUC_PRV { get; set; }
        public string CDG_TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public string MON_DOCU { get; set; }
        public Nullable<System.DateTime> FEC_DOCU { get; set; }
        public decimal IMP_PAG { get; set; }
        public decimal TIP_CMB { get; set; }
        public string SWT_ACT { get; set; }
        public string CDG_CCT { get; set; }
        public string CDG_TANA2 { get; set; }
        public string CDG_ANAL2 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string REFERENCIA1 { get; set; }
        public Nullable<System.DateTime> FECHA_LIQUIDA { get; set; }
        public string MON_CAJA { get; set; }
        public string NUM_REQUI { get; set; }
        public string CDG_SUCURSAL { get; set; }
        public string SCDG_CC { get; set; }
        public string CDG_BCO { get; set; }
        public string NUM_CTA { get; set; }
        public string NUM_CORB { get; set; }
    }
}
