//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CAJAB
    {
        public decimal ID_MOVIMIENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_TC { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
        public string GIRA_DETALLE { get; set; }
        public string OBSERVACION { get; set; }
        public string REF_CHOP { get; set; }
        public string MONEDA { get; set; }
        public decimal IMPORTE { get; set; }
        public string TIPO { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
