//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_EMPRESA()
        {
            this.OPE_SUCURSAL = new HashSet<OPE_SUCURSAL>();
        }
    
        public string CODIGO_EMPRESA { get; set; }
        public string RUC { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public string DNI_REPRESENTANTE { get; set; }
        public string REPRESENTANTE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public byte[] IMAGEN_HEADER { get; set; }
        public byte[] IMAGEN_FOOTER { get; set; }
        public string REFERENCIA1 { get; set; }
        public string REFERENCIA2 { get; set; }
        public byte[] IMAGEN_BACKGROUND { get; set; }
        public string EMPRESA_PRINCIPAL { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string NOTA { get; set; }
        public byte[] IMAGEN_PLAN { get; set; }
        public string C_ID { get; set; }
        public string C_ST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_SUCURSAL> OPE_SUCURSAL { get; set; }
    }
}
