//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PAGO_TRABAJADOR
    {
        public int ID_PERSONA { get; set; }
        public string RUC { get; set; }
        public string CDG_TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public decimal IMP_PAGO { get; set; }
        public string CDG_MON { get; set; }
        public decimal TIP_CMB { get; set; }
        public string NUM_COR { get; set; }
        public string NUM_CTA { get; set; }
        public string CDG_BCO { get; set; }
        public string NUM_CHEQ { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public System.DateTime FEC_PAGO { get; set; }
        public string HORA { get; set; }
        public string FECHA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string CDG_FPAG { get; set; }
        public string CDG_VEND { get; set; }
        public string CDG_MON_ORI { get; set; }
        public Nullable<decimal> IMP_PAGO_SOLES { get; set; }
        public Nullable<decimal> IMP_PAGO_DOLAR { get; set; }
    }
}
