//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_CONSUMO
    {
        public int ID_CONSUMO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal VENDIDO { get; set; }
        public decimal BAJA { get; set; }
        public int SECUENCIA { get; set; }
    }
}
