//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_RESULTADO_PRODUCTO
    {
        public decimal ID_PRODUCTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CDG_AGRUPACION { get; set; }
        public string TIPO_DATO { get; set; }
        public string VALOR_DEFECTO { get; set; }
        public string NOM_CAMPO { get; set; }
        public string FORMULA { get; set; }
        public string OPCIONES { get; set; }
        public Nullable<decimal> VMI_H { get; set; }
        public Nullable<decimal> VMA_H { get; set; }
        public Nullable<decimal> VMI_M { get; set; }
        public Nullable<decimal> VMA_M { get; set; }
        public string UNIDAD_VALOR { get; set; }
        public string VALOR_REFRENCIA { get; set; }
        public string METODO { get; set; }
    }
}
