//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_ORDEN_FABRICACION_SERIELOTE
    {
        public string CODIGO_OF { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string NUM_EMBALAJE { get; set; }
        public string SERIE { get; set; }
        public string LOTE { get; set; }
        public string UNIDAD { get; set; }
        public decimal CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
