//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_IMP_PRESUPUESTO
    {
        public decimal ID_PRESUPUESTO { get; set; }
        public string CODIGO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CDG_UNIDAD { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> PROBABILIDAD { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> PRECIOME { get; set; }
        public Nullable<decimal> SUBTOTALME { get; set; }
        public Nullable<decimal> TOTALME { get; set; }
    }
}
