//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_DOCUMENTO_VENTA
    {
        public decimal ID_DETALLLE { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal MONTO_EMPRESA { get; set; }
        public decimal MONTO_TRABAJADOR { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public int SECUENCIA { get; set; }
        public string NUMERO_COMANDA { get; set; }
        public string COMENTARIO { get; set; }
        public string INICIO { get; set; }
        public string FIN { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> DSCTO { get; set; }
        public Nullable<decimal> IMPORTE_DSCTO { get; set; }
        public Nullable<decimal> PRECIO_ORIGINAL { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public string CDG_PROD { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public Nullable<decimal> MARGEN { get; set; }
        public Nullable<decimal> IMPORTE_MARGEN { get; set; }
        public Nullable<decimal> ID_PEDIDO { get; set; }
        public Nullable<decimal> ID_DOCU { get; set; }
        public string TIPO_LISTA { get; set; }
        public Nullable<decimal> ID_PRODUCTO_PARENT { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> POR_PERCEPCION { get; set; }
        public Nullable<decimal> PERCEPCION { get; set; }
        public string OS { get; set; }
        public string FLAG_ADD { get; set; }
        public Nullable<decimal> VALOR_VEN { get; set; }
        public string UNID_VEN { get; set; }
        public Nullable<System.DateTime> FECHA_VEN { get; set; }
        public string CDG_KIT { get; set; }
        public string SWT_PIGV { get; set; }
        public string SWT_PROM { get; set; }
        public string SWT_IMP { get; set; }
        public Nullable<decimal> CANT_KIT { get; set; }
        public string SWT_DCOM { get; set; }
        public string SWT_FREE { get; set; }
        public string NOM_IMP { get; set; }
        public Nullable<decimal> SEC_PROD { get; set; }
        public string TIPO_AFEC_IGV { get; set; }
        public string CDG_TIPO_DETR { get; set; }
        public string GRUP_TIPO_AFEC_IGV { get; set; }
        public Nullable<decimal> POR_DETRACCION { get; set; }
        public Nullable<decimal> DETRACCION { get; set; }
        public string REFERENCIA1 { get; set; }
        public Nullable<decimal> POR_IGV { get; set; }
        public Nullable<decimal> VV { get; set; }
        public string CDG_VEND { get; set; }
    
        public virtual OPE_DOCUMENTO_VENTA OPE_DOCUMENTO_VENTA { get; set; }
    }
}
