//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CUENTA_CORRIENTE_CLIENTE
    {
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public int ID_PERSONA { get; set; }
        public string RUC_CLIENTE { get; set; }
        public string MONEDA { get; set; }
        public System.DateTime FECHA_DOCUMENTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal IMPORTE_DOCUMENTO { get; set; }
        public decimal PAGO_DOCUMENTO { get; set; }
        public string ESTADO { get; set; }
        public int ID_DOCUMENTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string PUNTO_VENTA { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string REFLETRA { get; set; }
    }
}
