//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CAJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_CAJA()
        {
            this.OPE_DETALLE_CAJA = new HashSet<OPE_DETALLE_CAJA>();
        }
    
        public string CDG_AREA { get; set; }
        public string NUM_CAJA { get; set; }
        public string NUM_CTA { get; set; }
        public string CDG_BCO { get; set; }
        public string CDG_FPAG { get; set; }
        public string NUM_CHEQ { get; set; }
        public string CDG_MON { get; set; }
        public System.DateTime FEC_CAJA { get; set; }
        public decimal SLD_CAJA { get; set; }
        public decimal IMP_CAJA { get; set; }
        public decimal TOT_CAJA { get; set; }
        public decimal MAX_CAJA { get; set; }
        public string SWT_CAJA { get; set; }
        public string CDG_TMOV { get; set; }
        public string NUM_COR { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FEC_CIERRE { get; set; }
        public string OBSERVACION { get; set; }
        public string CDG_OP { get; set; }
        public string CDG_OS { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string NUM_REQUI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_CAJA> OPE_DETALLE_CAJA { get; set; }
    }
}
