//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COMP_ELEC
    {
        public string CODI_EMPR { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
        public string TIPO_DOCU_CLIE { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MONEDA { get; set; }
        public decimal VVENTA { get; set; }
        public decimal IGV { get; set; }
        public decimal TOTAL { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
