//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_LIMPIEZA_HABITACION
    {
        public string HABITACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MOTIVO { get; set; }
        public string HORA { get; set; }
        public Nullable<decimal> ID_EMPLEADO { get; set; }
        public string ENTRADA { get; set; }
        public string TOALLAS { get; set; }
        public string SABANAS { get; set; }
        public string SALIDA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
