//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_ORDEN_COMPRA()
        {
            this.OPE_DETALLE_ORDEN_COMPRA = new HashSet<OPE_DETALLE_ORDEN_COMPRA>();
        }
    
        public int ID_OC { get; set; }
        public string CODIGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_PERSONA { get; set; }
        public string FORMA_PAGO { get; set; }
        public string MONEDA { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal PORCENTAJE_DSCTO { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal IGV { get; set; }
        public decimal MONTO { get; set; }
        public string ESTADO { get; set; }
        public string LUGAR_ENTREGA { get; set; }
        public string OBSERVACION { get; set; }
        public string CDG_COTI { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZACION { get; set; }
        public string USUARIO_AUTORIZA { get; set; }
        public string ATENCION { get; set; }
        public string REFERENCIA { get; set; }
        public string INCOTERMS { get; set; }
        public string SHIP_ORDER { get; set; }
        public string SHIPPING_MARKS { get; set; }
        public string SHIP_TO { get; set; }
        public string BILL_NET_PRICE_TO { get; set; }
        public string RESPONSABLE { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> PORCENTAJE_IGV { get; set; }
        public Nullable<decimal> VALOR_COMPRA { get; set; }
        public string TIPO_DOCU { get; set; }
        public string MEDIO_TRANSPORTE { get; set; }
        public string PAGO_ADELANTADO { get; set; }
        public Nullable<System.DateTime> FECHA_ESTIMADA_EMBARQUE { get; set; }
        public Nullable<System.DateTime> FECHA_ESTIMADA_LLEGADA { get; set; }
        public string ORDEN_PEDIDO { get; set; }
        public string MOTI_ORCO { get; set; }
        public string SWT_IGV { get; set; }
        public string ALMACEN { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string REF_NUM { get; set; }
        public string ENTREGA_MATERIAL { get; set; }
        public string ENTREGA_FACTURA { get; set; }
        public string NUM { get; set; }
        public Nullable<decimal> FLETE { get; set; }
        public Nullable<decimal> VALOR_AFECTO { get; set; }
        public Nullable<decimal> VALOR_INAFECTO { get; set; }
        public string REQUI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_ORDEN_COMPRA> OPE_DETALLE_ORDEN_COMPRA { get; set; }
    }
}
