//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PROVEEDOR_PRODUCTO
    {
        public int ID_PERSONA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string CDG_MON { get; set; }
        public decimal PRECIO { get; set; }
        public string NUMERO_PARTE { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
