//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PLAN_FACT_GASTO
    {
        public string TIPO { get; set; }
        public decimal ID_PROYECTO { get; set; }
        public string ANO { get; set; }
        public string CDG_CC { get; set; }
        public Nullable<decimal> ENERO { get; set; }
        public Nullable<decimal> FEBRERO { get; set; }
        public Nullable<decimal> MARZO { get; set; }
        public Nullable<decimal> ABRIL { get; set; }
        public Nullable<decimal> MAYO { get; set; }
        public Nullable<decimal> JUNIO { get; set; }
        public Nullable<decimal> JULIO { get; set; }
        public Nullable<decimal> AGOSTO { get; set; }
        public Nullable<decimal> SETIEMBRE { get; set; }
        public Nullable<decimal> OCTUBRE { get; set; }
        public Nullable<decimal> NOVIEMBRE { get; set; }
        public Nullable<decimal> DICIEMBRE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
