//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_SOLICITUD_VJEVTO
    {
        public decimal ID_SOLICITUD { get; set; }
        public string TIPO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string TIPO_AT { get; set; }
        public string CDG_VJE { get; set; }
        public string CDG_VTO { get; set; }
        public string CDG_PERSONAL { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal COSTO_UNITARIO { get; set; }
        public decimal CANT_PERSONA { get; set; }
        public decimal IMPORTE { get; set; }
        public string CDG_CECO { get; set; }
        public string OBSERVACION { get; set; }
        public string NOM_VJE { get; set; }
        public string NOM_VTO { get; set; }
    }
}
