//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_SOLICITUD_DOCUMENTO
    {
        public decimal ID_SOLICITUD { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UNIDAD { get; set; }
        public decimal SECUENCIA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public string AFECTO_IGV { get; set; }
        public string SWT_PIGV { get; set; }
        public string TIPO_AFEC_IGV { get; set; }
    }
}
