//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_FORMATO_LABVALOR
    {
        public string FORMATO { get; set; }
        public string TIPO { get; set; }
        public string COLOR { get; set; }
        public string ASPECTO { get; set; }
        public string DENSIDAD { get; set; }
        public string OLOR { get; set; }
        public string REACCION { get; set; }
        public string CEL_EPITELIALES { get; set; }
        public string PIOCITO { get; set; }
        public string LEUCOCITO { get; set; }
        public string HEMATIES { get; set; }
        public string CILINDRO { get; set; }
        public string CRISTALES { get; set; }
        public string OTROS { get; set; }
        public string GLUCOSA { get; set; }
        public string UROBILINOGENO { get; set; }
        public string SANGRE { get; set; }
        public string PROTEINA { get; set; }
        public string CUERPO_CETONICO { get; set; }
        public string NITRITO { get; set; }
        public string BILIRRUBINA { get; set; }
        public string ESTERASA_LEUCOCITANIA { get; set; }
        public string HEMOGLOBINA { get; set; }
        public string ACIDO_ASCORBICO { get; set; }
        public string LINFOCITO { get; set; }
        public string BASOFILO { get; set; }
        public string MONOCITO { get; set; }
        public string RANGO1 { get; set; }
        public string RANGO2 { get; set; }
        public string VALOR_REFERENCIAL1 { get; set; }
        public string VALOR_REFERENCIAL2 { get; set; }
        public string VALOR_REFERENCIAL3 { get; set; }
        public string VALOR_REFERENCIAL4 { get; set; }
        public string METODO1 { get; set; }
        public string METODO2 { get; set; }
        public string METODO3 { get; set; }
        public string METODO4 { get; set; }
        public string UND1 { get; set; }
        public string UND2 { get; set; }
        public string UND3 { get; set; }
        public string UND4 { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public string T5 { get; set; }
        public string T6 { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
