//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_LIBBCO1
    {
        public string CDG_BCO { get; set; }
        public string NUM_CTA { get; set; }
        public string NUM_COR { get; set; }
        public string NUM_ITM { get; set; }
        public string CDG_TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public string CDG_TMOV { get; set; }
        public decimal IMP_DEBE { get; set; }
        public decimal IMP_HABER { get; set; }
        public string CDG_TANA { get; set; }
        public string CDG_ANAL { get; set; }
        public string MON_ORI { get; set; }
        public string CDG_CC { get; set; }
        public Nullable<int> NUM_ITM2 { get; set; }
    }
}
