//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_LISTA_PRECIO2
    {
        public string CODIGO { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string ID_TIPO_CLIENTE { get; set; }
        public string MONEDA { get; set; }
        public decimal COSTO { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public decimal MARGEN { get; set; }
        public Nullable<decimal> PRECIO_VENTA2 { get; set; }
        public Nullable<decimal> PRECIO_VENTA3 { get; set; }
        public Nullable<decimal> PRECIO_VENTA4 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<decimal> MARGEN2 { get; set; }
        public Nullable<decimal> MARGEN3 { get; set; }
        public Nullable<decimal> MARGEN4 { get; set; }
    
        public virtual OPE_CLISTA_PRECIO OPE_CLISTA_PRECIO { get; set; }
    }
}
