//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SOLICITUD_DOCUMENTO
    {
        public decimal ID_SOLICITUD { get; set; }
        public string CODIGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MOTIVO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> ID_DOCUMENTO { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
        public string ESTADO { get; set; }
        public string MONEDA { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal ANTICIPO { get; set; }
        public decimal VALOR_VENTA { get; set; }
        public decimal POR_IGV { get; set; }
        public decimal IGV { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> ID_GUIA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
    }
}
