//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SUCURSAL
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string RUC { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO { get; set; }
        public string ES_PRINCIPAL { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string VALORIZA { get; set; }
        public string PEDIDO { get; set; }
        public string REFERENCIA1 { get; set; }
        public string VENTA { get; set; }
        public string IMPRESORA_MATRICIAL { get; set; }
        public string REFERENCIA2 { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string IMPRESORA_CAJA { get; set; }
        public string SWT_WEB { get; set; }
        public string ABR { get; set; }
    
        public virtual OPE_EMPRESA OPE_EMPRESA { get; set; }
    }
}
