//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CUOTA_DOCUMENTOVENTA
    {
        public decimal ID_DOCUMENTO { get; set; }
        public decimal NUM_CUOTA { get; set; }
        public decimal IMPORTE { get; set; }
        public System.DateTime FECHA_VCTO { get; set; }
    }
}
