//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_ORDEN_FABRICACION
    {
        public string CODIGO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public decimal planificado { get; set; }
        public Nullable<decimal> entregado { get; set; }
        public Nullable<decimal> requerido { get; set; }
        public Nullable<decimal> cant_base { get; set; }
        public Nullable<decimal> costo_promedio { get; set; }
        public Nullable<decimal> costo_promedio_d { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_d { get; set; }
        public string des_item { get; set; }
        public string ref1 { get; set; }
        public Nullable<decimal> secuencia { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual OPE_ORDEN_FABRICACION OPE_ORDEN_FABRICACION { get; set; }
    }
}
