//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_ORDEN_SERVICIO
    {
        public string CODIGO_SERVICIO { get; set; }
        public string CODIGO_PROD { get; set; }
        public string GLOSA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string REFERENCIA1 { get; set; }
        public string REFERENCIA2 { get; set; }
        public string REFERENCIA3 { get; set; }
        public string REFERENCIA4 { get; set; }
        public decimal SECUENCIA { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string CENTRO_COSTO { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
