//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COTIZACION_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_COTIZACION_VENTA()
        {
            this.OPE_ANEXO_COTIZACION = new HashSet<OPE_ANEXO_COTIZACION>();
            this.OPE_DETALLE_COTIZACION = new HashSet<OPE_DETALLE_COTIZACION>();
        }
    
        public decimal ID_COTIZACION { get; set; }
        public string NUMERO_COTIZACION { get; set; }
        public string CODIGO_VENDEDOR { get; set; }
        public string CODIGO_VENDEDOR_ASIGNADO { get; set; }
        public string CODIGO_CPAGO { get; set; }
        public string CODIGO_MONEDA { get; set; }
        public System.DateTime FECHA_COTIZACION { get; set; }
        public string NUMERO_OCLIENTE { get; set; }
        public decimal IMPORTE_STOT { get; set; }
        public decimal IMPORTE_DESCUENTO { get; set; }
        public decimal VALOR_VENTA { get; set; }
        public decimal IMPORTE_IGV { get; set; }
        public decimal IMPORTE_TOTAL { get; set; }
        public decimal PORCENTAJE_DESCUENTO { get; set; }
        public decimal PORCENTAJE_IGV { get; set; }
        public string OBSERVACION { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_CLIENTE_FACTURA { get; set; }
        public Nullable<decimal> IMPORTE_ISC { get; set; }
        public string CONTACTO { get; set; }
        public string EMAIL_CONTACTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string TIPO_FECHA_ENTREGA { get; set; }
        public int DIAS_ENTREGA { get; set; }
        public System.DateTime FECHA_ENTREGA { get; set; }
        public string USUARIO_AUTORIZA { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZACION { get; set; }
        public string LUGAR_ENTREGA { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public string REDONDEO { get; set; }
        public string VALIDEZ { get; set; }
        public string MOTIVO { get; set; }
        public string CORRELATIVO { get; set; }
        public string CENTRO_COSTO { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> ID_COTIZACION_PARENT { get; set; }
        public string TELEFONOS { get; set; }
        public string SUCURSAL { get; set; }
        public string TIPO_ENTREGA { get; set; }
        public Nullable<int> DIAS_ENTREGA2 { get; set; }
        public string OBSERVACION2 { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> ID_OPORTUNIDAD { get; set; }
        public string MOTIVO_PERDIDA { get; set; }
        public string COMPETENCIA { get; set; }
        public string NOTA_PERDIDA { get; set; }
        public string SEPARAR_STOCK { get; set; }
        public string TIPO_DSCTO { get; set; }
        public Nullable<decimal> ID_PROYECTO { get; set; }
        public string SWT_VISADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_ANEXO_COTIZACION> OPE_ANEXO_COTIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_COTIZACION> OPE_DETALLE_COTIZACION { get; set; }
    }
}
