//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_TARIFA_PRECIO
    {
        public decimal ID_TARIFA { get; set; }
        public string TEMPORADA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public decimal ALOJAMIENTO { get; set; }
        public decimal DESAYUNO { get; set; }
        public decimal MEDIA_PENSION { get; set; }
        public decimal PENSION_COMPLETA { get; set; }
        public decimal TODO_INCLUIDO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
