//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_PEDIDO()
        {
            this.OPE_ANEXO_PEDIDO = new HashSet<OPE_ANEXO_PEDIDO>();
            this.OPE_DETALLE_PEDIDO = new HashSet<OPE_DETALLE_PEDIDO>();
        }
    
        public decimal ID_PEDIDO { get; set; }
        public string NUMERO_PEDIDO { get; set; }
        public string CODIGO_VENDEDOR { get; set; }
        public string CODIGO_CPAGO { get; set; }
        public string CODIGO_MONEDA { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string NUMERO_OCLIENTE { get; set; }
        public decimal IMPORTE_STOT { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public decimal IMPORTE_IGV { get; set; }
        public decimal IMPORTE_DESCUENTO { get; set; }
        public decimal IMPORTE_TOTAL { get; set; }
        public decimal PORCENTAJE_DESCUENTO { get; set; }
        public decimal PORCENTAJE_IGV { get; set; }
        public string OBSERVACION { get; set; }
        public string ESTADO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public Nullable<decimal> IMPORTE_ISC { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public Nullable<int> ID_CLIENTE_FACTURA { get; set; }
        public string CODIGO_VENDEDOR_ASIGNADO { get; set; }
        public Nullable<System.DateTime> FECHA_PROGRAMADA { get; set; }
        public string FACTURA_ADELANTADA { get; set; }
        public string CONTACTO { get; set; }
        public string EMAIL_CONTACTO { get; set; }
        public string USUARIO_AUTORIZA { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZACION { get; set; }
        public string LUGAR_ENTREGA { get; set; }
        public Nullable<int> ID_COTIZACION { get; set; }
        public string ESTADO_FACTURA { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public string PUNTO_VENTA { get; set; }
        public string REDONDEO { get; set; }
        public string VALIDEZ { get; set; }
        public string MOTIVO { get; set; }
        public string CORRELATIVO { get; set; }
        public string CENTRO_COSTO { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> ID_OPORTUNIDAD { get; set; }
        public Nullable<decimal> VAL_PERCEPCION { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_PROGRAMADA_ENTREGA { get; set; }
        public string OBSERVACION2 { get; set; }
        public Nullable<decimal> PAX { get; set; }
        public string MESA { get; set; }
        public string PISO { get; set; }
        public string SWT_ESTA { get; set; }
        public string DELIVERY { get; set; }
        public string CDG_MENSAJERO { get; set; }
        public Nullable<System.DateTime> FECHA_FINALIZACION { get; set; }
        public Nullable<decimal> INICIAL { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public Nullable<decimal> SINICIAL { get; set; }
        public string TIPO_DSCTO { get; set; }
        public Nullable<decimal> ICBPER { get; set; }
        public string SWT_PD { get; set; }
        public string NUMPAIN { get; set; }
        public Nullable<decimal> ID_PROYECTO { get; set; }
        public Nullable<decimal> PORCENTAJE_INICIAL { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public Nullable<decimal> PUNTOS { get; set; }
        public Nullable<decimal> PRECIO_PUNTO { get; set; }
        public string PRIMER_ANO_USO { get; set; }
        public string CALENDARIO { get; set; }
        public Nullable<decimal> MONTO_INICIAL_HOY { get; set; }
        public Nullable<decimal> PORCENTAJE_INICIAL_HOY { get; set; }
        public string FORMA_DE_PAGO_1_INICIAL_HOY { get; set; }
        public string FP_GA { get; set; }
        public Nullable<decimal> MONTO_GA { get; set; }
        public Nullable<System.DateTime> VENC_GA { get; set; }
        public string BANCO_GA { get; set; }
        public string REF_GA { get; set; }
        public Nullable<System.DateTime> FECHA_PROCESABLE { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<decimal> CANTIDAD_ANO_CONTRATO { get; set; }
        public Nullable<decimal> MONTO_A_FINANCIAR { get; set; }
        public Nullable<decimal> PORCENTAJE_MONTO_FINANCIAR { get; set; }
        public Nullable<decimal> NUM_CUOTA_FINANCIAR { get; set; }
        public Nullable<decimal> PORCENTAJE_INTERES_MENSUAL { get; set; }
        public Nullable<decimal> MONTO_CUOTA_MENSUAL { get; set; }
        public Nullable<System.DateTime> VENC_PRIMERA_CUOTA { get; set; }
        public string SWT_WEB { get; set; }
        public string CDG_SCECO { get; set; }
        public Nullable<decimal> IdOrder { get; set; }
        public string OrderGuid { get; set; }
        public Nullable<decimal> CustomerId { get; set; }
        public string OrdeStatus { get; set; }
        public string PaymentStatusId { get; set; }
        public string PaymentMethodSystemName { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> PaidDateUtc { get; set; }
        public string CustomerIp { get; set; }
        public Nullable<decimal> PaymentMethodAdditionalFeeInclTax { get; set; }
        public Nullable<decimal> PaymentMethodAdditionalFeeExclTax { get; set; }
        public string ESTADOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_ANEXO_PEDIDO> OPE_ANEXO_PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_PEDIDO> OPE_DETALLE_PEDIDO { get; set; }
    }
}
