//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_REQUERIMIENTO
    {
        public string CODIGO_REQUERIMIENTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string PRIORIDAD { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_ATENCION { get; set; }
        public string HORA_ATENCION { get; set; }
        public string CDG_INGENIERO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CDG_VEND_CREACION { get; set; }
        public string CDG_VEND_ASIGNADO { get; set; }
        public string TIPO_REQU { get; set; }
        public string CENTRO_COSTO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD_PEDIDA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<int> ID_OC { get; set; }
        public Nullable<decimal> CANTIDAD_INGRESADA { get; set; }
        public Nullable<int> SECUENCIA { get; set; }
        public string CDG_PLAN { get; set; }
        public string CDG_ORD { get; set; }
        public Nullable<int> ID_PRODUCTO_OF { get; set; }
        public string CDG_SERV { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CDG_OP { get; set; }
        public Nullable<int> SECUENCIA_OC { get; set; }
        public string CDG_SCC { get; set; }
    }
}
