//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PARQUEO_VEHICULO
    {
        public decimal ID_MOVIMIENTO { get; set; }
        public string NUM_COCHERA { get; set; }
        public string NUM_PLACA { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string HORA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public string HORA_SALIDA { get; set; }
        public string TIPO_VEHICULO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string DESCRIPCION_VEHICULO { get; set; }
        public Nullable<decimal> TARIFA_IATP { get; set; }
        public Nullable<decimal> IMPORTE_IATP { get; set; }
        public Nullable<decimal> HORA_IATP { get; set; }
        public Nullable<decimal> MIN_IATP { get; set; }
    }
}
