//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_REFERENCIA_BANCARIA
    {
        public decimal SECUENCIA { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
        public string MONEDA { get; set; }
        public string CCI { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
