//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_PAGO_CLIENTE
    {
        public string CODIGO_EMPRESA { get; set; }
        public string NUMERO_COBRO { get; set; }
        public string MONEDA { get; set; }
        public decimal IMPORTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string COBRADOR { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public string BANCO { get; set; }
        public string NUM_CTA { get; set; }
        public string NUM_COR { get; set; }
        public string REF_BANC { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string CAJA { get; set; }
        public string SWT_CUO { get; set; }
        public Nullable<decimal> IMPORTE_PAGA { get; set; }
        public Nullable<decimal> IMPORTE_VUELTO { get; set; }
    }
}
