//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CALCULO_UNIEPP
    {
        public decimal ID_PARTIDA { get; set; }
        public decimal TC_EMP { get; set; }
        public decimal HORA_MES_EMP { get; set; }
        public Nullable<decimal> TC_REF1 { get; set; }
        public Nullable<decimal> HORA_MES_REF1 { get; set; }
        public decimal PRECIO_UNITARIO_EMP { get; set; }
        public decimal COSTO_MENSUAL_EMP { get; set; }
        public decimal PRECIO_UNITARIO_RE1 { get; set; }
        public decimal COSTO_MENSUAL_REF1 { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
