//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_SEGUIMIENTO_COTI
    {
        public decimal ID_SECUENCIA { get; set; }
        public decimal ID_COTIZACION { get; set; }
        public Nullable<decimal> ANO_CIERRE { get; set; }
        public string MES_CIERRE { get; set; }
        public Nullable<decimal> ANO_ENTREGA { get; set; }
        public string MES_ENTREGA { get; set; }
        public System.DateTime FECHA_SEGUIMIENTO { get; set; }
        public System.DateTime FECHA_PROX_SEG { get; set; }
        public decimal PROB_CIERRE { get; set; }
        public decimal PORC_AVANCE { get; set; }
        public string COMENTARIO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
