//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_REFERENCIA_PERSONA2
    {
        public string TIPO_PERSONA { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string CODIGO { get; set; }
        public string RUC { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string DIRECCION { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL_FE { get; set; }
        public string PAGINA_WEB { get; set; }
        public string ESTADO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
