//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_OFPR_PRODUCTO
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string ID_TIPO_CLIENTE { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal DESCUENTO1 { get; set; }
        public decimal DESCUENTO2 { get; set; }
        public Nullable<decimal> CANTIDAD2 { get; set; }
        public Nullable<decimal> CANTIDAD3 { get; set; }
        public Nullable<decimal> CANTIDAD4 { get; set; }
        public Nullable<decimal> DESCUENTO3 { get; set; }
        public Nullable<decimal> DESCUENTO4 { get; set; }
    }
}
