//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COMISION_CONTRATO
    {
        public decimal ID_PEDIDO { get; set; }
        public string CDG_CARGO { get; set; }
        public decimal PORCENTAJE1 { get; set; }
        public Nullable<decimal> PORCENTAJE2 { get; set; }
        public decimal TOTAL_CONTRATO { get; set; }
        public decimal IMPORTE_COMISION { get; set; }
        public System.DateTime FECHA_CALCULO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
    }
}
