//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_ODOCUMENTO_COMPRA
    {
        public string NUM_COR { get; set; }
        public string TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public string RUC { get; set; }
        public string TDOC_COMP { get; set; }
        public string NUM_DOCU_COMP { get; set; }
        public string RUC_COMP { get; set; }
        public decimal ID_PERSONA { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public decimal IMPORTE_TRANSACCION { get; set; }
        public decimal IMPORTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string AUTO_G { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
