//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_ACTIVO_FIJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_DETALLE_ACTIVO_FIJO()
        {
            this.OPE_ASIGNACION_ACTIVO_FIJO = new HashSet<OPE_ASIGNACION_ACTIVO_FIJO>();
        }
    
        public decimal daf_id { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string daf_serie { get; set; }
        public string daf_marca { get; set; }
        public string daf_modelo { get; set; }
        public Nullable<int> daf_cantidad { get; set; }
        public string daf_numero_factura { get; set; }
        public string id_moneda { get; set; }
        public Nullable<int> proveedor_codigo { get; set; }
        public Nullable<System.DateTime> daf_fecha_adquisicion { get; set; }
        public Nullable<System.DateTime> daf_fecha_capitalizacion { get; set; }
        public Nullable<decimal> daf_valor_adquisicion { get; set; }
        public string daf_clase { get; set; }
        public string daf_nivel_absolescencia { get; set; }
        public string daf_uso { get; set; }
        public string daf_estado_fisico { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_ASIGNACION_ACTIVO_FIJO> OPE_ASIGNACION_ACTIVO_FIJO { get; set; }
    }
}
