//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_REQUISICION
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string CODIGO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIDO { get; set; }
        public string NUM_REQUI { get; set; }
        public string ESTADO { get; set; }
        public string SOLICITANTE { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
        public string MOD_PAGO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> POR_IGV { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> VALOR_COMPRA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACION { get; set; }
        public string SWT_REQ { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
        public string CTA_CTE { get; set; }
        public string VEHICULO { get; set; }
        public string OBSERVACION2 { get; set; }
        public string CDG_BCO_EMP { get; set; }
        public string CTA_CTE_EMP { get; set; }
        public Nullable<System.DateTime> FECH_MOV_BCO { get; set; }
        public string NUM_REF { get; set; }
        public Nullable<decimal> IMP_BCO { get; set; }
        public string DOCS { get; set; }
        public Nullable<decimal> TASA { get; set; }
        public Nullable<decimal> PERCEPCION { get; set; }
        public Nullable<decimal> ID_OC { get; set; }
    }
}
