//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DETALLE_CALCULO_UNIEPP
    {
        public decimal ID_PARTIDA { get; set; }
        public decimal ID_MATERIAL { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal PRECIO_ORIGINAL_EMP { get; set; }
        public string MONEDA_EMP { get; set; }
        public decimal PRECIO_MN_EMP { get; set; }
        public decimal CANT_CONSUMO_ANUAL_CAPATAZ_EMP { get; set; }
        public decimal PROPORCION_USO_CAPATAZ_EMP { get; set; }
        public decimal CANT_CONSUMO_ANUAL_OPERARIO_EMP { get; set; }
        public decimal PROPORCION_USO_OPERARIO_EMP { get; set; }
        public decimal CANT_CONSUMO_ANUAL_AYUDANTE_EMP { get; set; }
        public decimal PROPORCION_USO_AYUDANTE_EMP { get; set; }
        public decimal CANT_CONSUMO_ANUAL_OTRO_EMP { get; set; }
        public decimal PROPORCION_USO_OTRO_EMP { get; set; }
        public decimal PRECIO_ORIGINAL_REF1 { get; set; }
        public string MONEDA_REF1 { get; set; }
        public decimal PRECIO_MN_REF1 { get; set; }
        public decimal CANT_CONSUMO_ANUAL_CAPATAZ_REF1 { get; set; }
        public decimal PROPORCION_USO_CAPATAZ_REF1 { get; set; }
        public decimal CANT_CONSUMO_ANUAL_OPERARIO_REF1 { get; set; }
        public decimal PROPORCION_USO_OPERARIO_REF1 { get; set; }
        public decimal CANT_CONSUMO_ANUAL_AYUDANTE_REF1 { get; set; }
        public decimal PROPORCION_USO_AYUDANTE_REF1 { get; set; }
        public decimal CANT_CONSUMO_ANUAL_OTRO_REF1 { get; set; }
        public decimal PROPORCION_USO_OTRO_REF1 { get; set; }
    }
}
