//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COMPROMISO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPE_COMPROMISO()
        {
            this.OPE_DETALLE_COMPROMISO = new HashSet<OPE_DETALLE_COMPROMISO>();
        }
    
        public string num_comp { get; set; }
        public string ano { get; set; }
        public string mes { get; set; }
        public string cdg_tmov { get; set; }
        public string cdg_pla { get; set; }
        public string cdg_bco { get; set; }
        public string num_cta { get; set; }
        public string NUM_COR { get; set; }
        public string cdg_mon { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> tea { get; set; }
        public string swt_est { get; set; }
        public Nullable<decimal> tip_cmb { get; set; }
        public Nullable<System.DateTime> fec_docu { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string obs { get; set; }
        public string beneficiario { get; set; }
        public Nullable<System.DateTime> fecha_plazo { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public Nullable<decimal> ID_PERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPE_DETALLE_COMPROMISO> OPE_DETALLE_COMPROMISO { get; set; }
    }
}
