//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_NI_GASTO_IMPORTACION
    {
        public string niga_file_importacion { get; set; }
        public string niga_ingreso { get; set; }
        public decimal niga_porcentaje { get; set; }
        public string niga_prorrateo { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string niga_tipo_documento { get; set; }
        public string niga_num_docu { get; set; }
        public string niga_ruc { get; set; }
        public Nullable<decimal> niga_importe_dolar { get; set; }
        public Nullable<decimal> niga_tc { get; set; }
        public Nullable<int> secuencia { get; set; }
        public string cuenta { get; set; }
        public string glosa { get; set; }
        public Nullable<int> secuencia_docu { get; set; }
        public string cdg_gasto { get; set; }
        public string cdg_costeo { get; set; }
    }
}
