//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_GG_PRESUPUESTO
    {
        public decimal ID_PRESUPUESTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CDG_TABLA { get; set; }
        public string CODIGO { get; set; }
        public string CDG_UNIDAD { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> PARTICIPACION { get; set; }
        public Nullable<decimal> TIEMPO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<decimal> PARCIAL { get; set; }
        public Nullable<decimal> SUELDOME { get; set; }
        public Nullable<decimal> PARCIALME { get; set; }
    }
}
