//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_COSTO_REAL_OF
    {
        public string anomes { get; set; }
        public string id_of { get; set; }
        public decimal id_producto { get; set; }
        public decimal id_insumo { get; set; }
        public decimal costo_sol { get; set; }
        public decimal costo_dol { get; set; }
        public string usuario_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public decimal cantidad_producidad { get; set; }
        public Nullable<decimal> id_guia { get; set; }
        public Nullable<decimal> cantidad_insumo { get; set; }
        public Nullable<decimal> saldo_guia { get; set; }
        public Nullable<decimal> id_guia_ing { get; set; }
    }
}
