//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_DOCUMENTO_COMPRA2
    {
        public decimal ID_DOCUMENTO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string RUC_PRV { get; set; }
        public string CDG_TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public string CDG_AFEC { get; set; }
        public string CDG_CPAG { get; set; }
        public string CDG_MON { get; set; }
        public System.DateTime FEC_DOCU { get; set; }
        public System.DateTime FEC_VCTO { get; set; }
        public Nullable<System.DateTime> FEC_CANC { get; set; }
        public decimal VAL_FSUB { get; set; }
        public decimal VAL_FDES { get; set; }
        public decimal VAL_FLET { get; set; }
        public decimal VAL_FIGV { get; set; }
        public decimal VAL_FTOT { get; set; }
        public Nullable<decimal> VAL_FPAG { get; set; }
        public string OBS_FPRV { get; set; }
        public string SWT_EST { get; set; }
        public string SWT_OCOM { get; set; }
        public string NUM_ORIG { get; set; }
        public string NUM_VOUC { get; set; }
        public Nullable<System.DateTime> FEC_CMP { get; set; }
        public Nullable<decimal> POR_TIGV { get; set; }
        public Nullable<decimal> VAL_FINT { get; set; }
        public string NUM { get; set; }
        public string NUM_POLI { get; set; }
        public string SWT_POLI { get; set; }
        public string BAS_PORR { get; set; }
        public string EST_POLI { get; set; }
        public Nullable<decimal> IMP_ISC { get; set; }
        public string CDG_TREF { get; set; }
        public string NUM_REF { get; set; }
        public Nullable<System.DateTime> FEC_REF { get; set; }
        public Nullable<decimal> IMP2 { get; set; }
        public Nullable<decimal> IMP3 { get; set; }
        public Nullable<decimal> SUB2 { get; set; }
        public Nullable<decimal> POR_TPER { get; set; }
        public Nullable<decimal> VAL_FPER { get; set; }
        public Nullable<System.DateTime> FEC_PGOD { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string AFECTA_TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_DETRA { get; set; }
        public string NUMERO_DETRA { get; set; }
        public Nullable<decimal> TASA_DETRA { get; set; }
        public string ANTICIPO { get; set; }
        public string TIPO_REF_IMP { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string REF1 { get; set; }
        public string REFE_CORR { get; set; }
        public Nullable<decimal> ID_OC { get; set; }
        public Nullable<decimal> POR_TIR { get; set; }
        public string NUM_REQ { get; set; }
        public Nullable<decimal> FLETE { get; set; }
        public string TIPO_DSCTO { get; set; }
        public Nullable<decimal> ID_CONVENIO { get; set; }
        public Nullable<decimal> ID_PRODLAB { get; set; }
        public Nullable<decimal> NUMSEC { get; set; }
    }
}
