//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_OCDC_PRORRATEO
    {
        public Nullable<decimal> ID_OC { get; set; }
        public Nullable<decimal> ID_DOCUMENTO { get; set; }
        public Nullable<decimal> ID_PRODUCTO { get; set; }
        public string CDG_GASTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CDG_CC { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal PORCENTAJE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
