//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPE_CONVENIO_PRUEBA
    {
        public decimal ID_CONVENIO { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal NUM_SEC { get; set; }
        public decimal COSTO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_ATENCION { get; set; }
        public Nullable<decimal> ID_MEDICO { get; set; }
    }
}
