//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_COBRANZA_CLIENTE
    {
        public string ID_TIPO_DOCUMENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string ID_MONEDA { get; set; }
        public string MONEDA { get; set; }
        public string FORMA_PAGO { get; set; }
        public string FORMA_PAGO_DESC { get; set; }
        public string CHEQUE { get; set; }
        public decimal IMPORTE_COBRO { get; set; }
        public System.DateTime FECHA_COBRO { get; set; }
        public string NUMERO_COBRO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string ID_MONEDA_ORI { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public string ORDEN_PEDIDO { get; set; }
        public Nullable<decimal> ID_PEDIDO { get; set; }
    }
}
