//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_KARDEX
    {
        public decimal ID_PRODUCTO { get; set; }
        public decimal VEGR_ID { get; set; }
        public string TIPO_MOVI { get; set; }
        public string ALMACEN { get; set; }
        public System.DateTime VEGR_FECHA_SALIDA { get; set; }
        public string ALMACEN_NOMBRE { get; set; }
        public string PERSONA { get; set; }
        public string NUMERO { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public Nullable<decimal> DVEGR_PRECIO { get; set; }
        public Nullable<decimal> DVEGR_COSTO { get; set; }
        public Nullable<decimal> INGRESO { get; set; }
        public Nullable<decimal> SALIDA { get; set; }
        public int SALDO { get; set; }
        public Nullable<int> ID_DOCUMENTO_PARENT { get; set; }
        public string TIPO_GUIA { get; set; }
        public Nullable<decimal> ID_OC { get; set; }
        public Nullable<decimal> ID_DOCO { get; set; }
    }
}
