//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_DSTOCK_LOTE
    {
        public string CODIGO_SUCURSAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public Nullable<decimal> stk_ing { get; set; }
        public Nullable<decimal> stk_sal { get; set; }
        public Nullable<decimal> stk_act { get; set; }
        public string LOTE { get; set; }
    }
}
