//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_OBTENER_VENTA_MASIVA3
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string NUMERO { get; set; }
        public string NOMBRE { get; set; }
        public short DESAYUNO { get; set; }
        public short ALMUERZO { get; set; }
        public short CENA { get; set; }
        public Nullable<short> LONCHE { get; set; }
        public Nullable<short> BREAK1 { get; set; }
        public Nullable<short> REFERENCIA1 { get; set; }
        public Nullable<short> REFERENCIA2 { get; set; }
        public Nullable<short> REFERENCIA3 { get; set; }
        public Nullable<short> REFERENCIA4 { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string CLIENTE { get; set; }
    }
}
