//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_NS_GUIAS_REMISION
    {
        public decimal ID_OC { get; set; }
        public string CODIGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string PROVEEDOR { get; set; }
        public string ESTADO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> ID_PROVEEDOR { get; set; }
        public string TDOC { get; set; }
        public string NUMDOC { get; set; }
    }
}
