//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_PORCENTAJE_COTIZACION
    {
        public decimal ID_COTIZACION { get; set; }
        public System.DateTime FECHA_COTIZACION { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ANO { get; set; }
        public Nullable<int> NMES { get; set; }
        public string MES { get; set; }
        public string CODIGO_VENDEDOR_ASIGNADO { get; set; }
        public string VENDEDOR { get; set; }
        public string ESTADO { get; set; }
    }
}
