//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_GUIA_DREMISIONP
    {
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<System.DateTime> VEGR_FECHA_SALIDA { get; set; }
        public string ALMACEN { get; set; }
    }
}
