//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_VENTA_RENTABILIDADCE
    {
        public decimal ID_PRODUCTO { get; set; }
        public string TIPO_PROD { get; set; }
        public string CATEGORIA { get; set; }
        public string GRUPO { get; set; }
        public string SUBGRUPO { get; set; }
        public string CDG_OP { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string MONEDA { get; set; }
        public string MON { get; set; }
        public int ID_PERSONA { get; set; }
        public string CLIENTE { get; set; }
        public string ID_TIPO_DOCUMENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NRO_DOCUMENTO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string ID_MARCA { get; set; }
        public string MARCA { get; set; }
        public string ID_MODELO { get; set; }
        public string MODELO { get; set; }
        public Nullable<decimal> PRECIO_S { get; set; }
        public Nullable<decimal> PRECIO_D { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> VALOR_VENTA_SIN_NC_S { get; set; }
        public Nullable<decimal> VALOR_VENTA_SIN_NC_D { get; set; }
        public Nullable<decimal> VALOR_VENTA_CON_NC_S { get; set; }
        public Nullable<decimal> VALOR_VENTA_CON_NC_D { get; set; }
        public decimal COSTOPROM_SOLES { get; set; }
        public decimal COSTOPROM_DOLAR { get; set; }
        public decimal COSTOT_SOLES { get; set; }
        public decimal COSTOT_DOLAR { get; set; }
        public Nullable<decimal> MARGEN_SOLES { get; set; }
        public Nullable<decimal> MARGEN_DOLAR { get; set; }
        public Nullable<decimal> POR_MARGEN { get; set; }
        public string ID_TIPO_PRODUCTO { get; set; }
        public string ID_CATEGORIA { get; set; }
        public string ID_GRUPO { get; set; }
        public string ID_SUBGRUPO { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public string REFVEND { get; set; }
        public string VENDEDOR { get; set; }
        public Nullable<int> ANO { get; set; }
        public Nullable<int> MES { get; set; }
        public string TRIMESTRE { get; set; }
        public string SEMESTRE { get; set; }
    }
}
