//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_CAJAB
    {
        public string FEC_DOCU { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> ANO { get; set; }
        public string CODIGO { get; set; }
        public string NUM_REF { get; set; }
        public string GIRADO { get; set; }
        public string DES_PRV { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> INGRESOME { get; set; }
        public Nullable<decimal> SALIDAME { get; set; }
        public int SALDO_RESTANTEME { get; set; }
        public string FECHA_TC { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> INGRESOMN { get; set; }
        public Nullable<decimal> EGRESOMN { get; set; }
        public int TIPO { get; set; }
        public string CDG_BCO_EMP { get; set; }
        public string CTA_CTE_EMP { get; set; }
        public Nullable<System.DateTime> FECH_MOV_BCO { get; set; }
        public string MON { get; set; }
    }
}
