//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_OBTENER_VENTA_MASIVA_CONSOLIDADO
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string TIPO_TRAB { get; set; }
        public string RUC { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string NOMBRE { get; set; }
        public string EMPRESA { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<decimal> DESAYUNO { get; set; }
        public Nullable<decimal> ALMUERZO { get; set; }
        public Nullable<decimal> CENA { get; set; }
        public Nullable<decimal> LONCHE { get; set; }
        public Nullable<decimal> BREAK1 { get; set; }
        public Nullable<decimal> REFERENCIA1 { get; set; }
        public Nullable<decimal> REFERENCIA2 { get; set; }
        public Nullable<decimal> REFERENCIA3 { get; set; }
        public Nullable<decimal> REFERENCIA4 { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    }
}
