//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_COTIZACION_KIT
    {
        public decimal ID_COTIZACION { get; set; }
        public string CDG_KIT { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CANT_KIT { get; set; }
        public string UNIDAD { get; set; }
    }
}
