//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_ORDEN_COMPRA
    {
        public string CODIGO { get; set; }
        public int ID_OC { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> ID_REQ { get; set; }
        public string RESPONSABLE { get; set; }
        public int ID_PRODUCTO { get; set; }
    }
}
