//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_STOCK
    {
        public decimal ID_PRODUCTO { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string ALMACEN { get; set; }
        public int STOCK_INICIAL { get; set; }
        public Nullable<decimal> STOCK_INGRESO { get; set; }
        public Nullable<decimal> STOCK_SALIO { get; set; }
        public Nullable<decimal> STOCK_ACTUAL { get; set; }
        public Nullable<decimal> STOCK_INGRESO2 { get; set; }
        public Nullable<decimal> STOCK_SALIO2 { get; set; }
        public Nullable<decimal> STOCK_ACTUAL2 { get; set; }
    }
}
