//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_DPSTOCKUBI
    {
        public decimal ID_DOCUMENTO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string TIPO_GUIA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string LOTE { get; set; }
        public string SERIE { get; set; }
        public string CODIGO_UNIDAD { get; set; }
        public decimal INGRESO { get; set; }
        public decimal SALIDA { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string CODIGO_ZONA { get; set; }
        public string COLUMNA { get; set; }
        public string FILA { get; set; }
    }
}
