//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_OBTENER_VENTA_MASIVA
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string NOMBRE { get; set; }
        public int DESAYUNO { get; set; }
        public int ALMUERZO { get; set; }
        public int CENA { get; set; }
        public int LONCHE { get; set; }
        public int BREAK1 { get; set; }
        public int REFERENCIA1 { get; set; }
        public int REFERENCIA2 { get; set; }
        public int REFERENCIA3 { get; set; }
        public int REFERENCIA4 { get; set; }
    }
}
