//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_GUIA_FECHAALMACENGUIA
    {
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public string NUM_REF { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string ALMACEN { get; set; }
        public string NUMERO { get; set; }
    }
}
