//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_SAL_INV_POR_MOV3
    {
        public string CODIGO_EMPRESA { get; set; }
        public string ALMACEN { get; set; }
        public Nullable<int> ANO { get; set; }
        public Nullable<int> MES { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> INGRESO { get; set; }
        public Nullable<decimal> SALIDA { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public int SECUENCIA { get; set; }
        public string TIPO_GUIA { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string PERSONA { get; set; }
        public string NUMERO { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public string MOVIMIENTO { get; set; }
        public decimal ID_OC { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string OC { get; set; }
        public string OP { get; set; }
        public string ID_CATEGORIA { get; set; }
        public string LOTESERIE { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
    }
}
