//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_CON_PLA
    {
        public string ANO { get; set; }
        public int MES { get; set; }
        public string CON { get; set; }
        public decimal valDet { get; set; }
        public string CDG_PLANILLA { get; set; }
        public string TIPO_TRAB { get; set; }
        public string CUENTATD { get; set; }
        public string CUENTAOD { get; set; }
        public string CUENTATH { get; set; }
        public string CUENTAOH { get; set; }
    }
}
