//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_GUIA_DREMISION
    {
        public string TIPO_MOVIMIENTO { get; set; }
        public string COSTO_AUTOMATICO { get; set; }
        public decimal VEGR_ID { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public string CDG_REF { get; set; }
        public string TIPO_MOVI { get; set; }
        public string ALMACEN { get; set; }
        public string ALMACEN_NOMBRE { get; set; }
        public string CDG_PROD { get; set; }
        public string CDG_BARRA { get; set; }
        public string NOM_PROD { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> DVEGR_PRECIO { get; set; }
        public Nullable<decimal> DVEGR_COSTO { get; set; }
        public Nullable<decimal> DVEGR_DGUI { get; set; }
        public Nullable<System.DateTime> VEGR_FECHA_SALIDA { get; set; }
        public string TIPO_GUIA { get; set; }
        public Nullable<decimal> COOC_ID { get; set; }
        public string CDG_OC { get; set; }
        public string CDG_OP { get; set; }
        public string PERSONA { get; set; }
        public string OF_ID { get; set; }
        public string ID_MONEDA { get; set; }
        public Nullable<decimal> COSTO_COMPRA { get; set; }
        public Nullable<decimal> COSTO_DOCU { get; set; }
        public decimal COSTO_OC { get; set; }
        public string ID_MONEDA_OC { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string TRA { get; set; }
        public string REA { get; set; }
        public Nullable<decimal> PRECIO_DOLAR { get; set; }
        public Nullable<decimal> COSTO_DOLAR { get; set; }
        public Nullable<decimal> IMPORTE_SOLES { get; set; }
        public Nullable<decimal> IMPORTE_DOLAR { get; set; }
        public string NUMERO_DOCU { get; set; }
        public string OFS { get; set; }
        public int ORDEN { get; set; }
        public Nullable<int> ID_DOCUMENTO_PARENT { get; set; }
        public Nullable<decimal> PV_SOLES { get; set; }
        public Nullable<decimal> PV_DOLAR { get; set; }
        public Nullable<decimal> ID_RELA { get; set; }
        public string NUMERO { get; set; }
        public string ID_CATEGORIA { get; set; }
    }
}
