//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_SAL_INV_POR_MOV
    {
        public string CODIGO_EMPRESA { get; set; }
        public string ALMACEN { get; set; }
        public Nullable<int> ANO { get; set; }
        public Nullable<int> MES { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public Nullable<decimal> INGRESO { get; set; }
        public Nullable<decimal> SALIDA { get; set; }
        public Nullable<decimal> INGRESO2 { get; set; }
        public Nullable<decimal> SALIDA2 { get; set; }
    }
}
