//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_MOVIMIENTO_IMPORTACION
    {
        public string ORDEN_COMPRA { get; set; }
        public System.DateTime FECHA_OC { get; set; }
        public string CARPETA { get; set; }
        public string NOM_CARPETA { get; set; }
        public string NOTA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string RUC { get; set; }
        public string PROVEEDOR { get; set; }
        public string PA { get; set; }
        public string MODELO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> FOB_UNIT { get; set; }
        public Nullable<decimal> CIMP_UNIT { get; set; }
        public Nullable<decimal> CFOB_TOTAL { get; set; }
        public Nullable<decimal> CIMP_TOTAL { get; set; }
        public Nullable<decimal> RATIO_IMP { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string ID_MONEDA { get; set; }
        public string ESTADO { get; set; }
        public string COOC_ESTADO { get; set; }
        public Nullable<decimal> FLETE { get; set; }
        public Nullable<decimal> CFR { get; set; }
        public Nullable<decimal> SEGURO { get; set; }
        public Nullable<decimal> CIF { get; set; }
        public Nullable<decimal> AD_VALOREM { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> IPM { get; set; }
    }
}
