//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_VENTA_COMENSAL
    {
        public string CODIGO { get; set; }
        public string RUC { get; set; }
        public string COMENSAL { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string TIPO_TRABAJADOR { get; set; }
    }
}
