//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_EGRESOS
    {
        public string TURNO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public string REGISTRO { get; set; }
        public string OPERACION { get; set; }
        public string NOM_OPERACION { get; set; }
        public string PERSONA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
    }
}
