//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_PRODUCTO_MAS_VENDIDO_MONTO
    {
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public string MONEDA { get; set; }
        public string MESA { get; set; }
        public string MOZO { get; set; }
    }
}
