//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_OBTENER_DOCUMENTO2
    {
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string CODIGO_SUCURSAL2 { get; set; }
        public string CODIGO { get; set; }
        public string TRAB2 { get; set; }
        public string TIPO_TRABAJADOR { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string FECHA_REGISTRO { get; set; }
        public decimal SUB_TOTAL { get; set; }
    }
}
