//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPEVW_PAGO_BANCO
    {
        public string ID_TIPO_DOCUMENTO { get; set; }
        public int PROVEEDOR_CODIGO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string ID_MONEDA { get; set; }
        public string ID_MONEDA_ORI { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public string MONEDA { get; set; }
        public string CDG_FPAG { get; set; }
        public string FORMA_PAGO_DESC { get; set; }
        public string BANCO { get; set; }
        public string NUMERO_CHEQUE { get; set; }
        public decimal IMPORTE_PAGO { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public string NUM_COR { get; set; }
    }
}
