//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_KARDEX
    {
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> MES { get; set; }
        public string ALMACEN_NOMBRE { get; set; }
        public string CDG_PROD { get; set; }
        public string CDG_BARRA { get; set; }
        public string NOM_PROD { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACION { get; set; }
        public string TIPO_GUIA { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public string NUMERO_DOCU { get; set; }
        public string NUMERO_REF { get; set; }
        public string CDG_OC { get; set; }
        public string CDG_OP { get; set; }
        public string PERSONA { get; set; }
        public string TIPO_TRANSACION { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> IMPSOLES_VENTA { get; set; }
        public Nullable<decimal> IMPDOLAR_VENTA { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> COSTOD { get; set; }
        public Nullable<decimal> COSTOUNIT_SOLES { get; set; }
        public Nullable<decimal> COSTOUNIT_DOLARES { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
    }
}
