//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_DOCUMENTO_PROVEEDOR
    {
        public string RUC { get; set; }
        public string PERSONA { get; set; }
        public string ID_TD { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public string MONEDA { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> IMPORTE_DOCUMENTO { get; set; }
        public Nullable<decimal> PAGO_DOCUMENTO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string ESTADO { get; set; }
        public string NUM_REF { get; set; }
        public string UBICACION { get; set; }
        public string BANCO { get; set; }
    }
}
