//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_KARDEX_SERIES
    {
        public string ALMACEN { get; set; }
        public string CDG_PROD { get; set; }
        public string CDG_BARRA { get; set; }
        public string NOM_PROD { get; set; }
        public string TIPO_MOVI { get; set; }
        public string TIPO_GUIA { get; set; }
        public string CODIGO_GENERADO { get; set; }
        public string CDG_REF { get; set; }
        public string TIPO_TRANSACION { get; set; }
        public decimal CANTIDAD { get; set; }
        public string LOTE { get; set; }
        public string SERIE { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> COSTOD { get; set; }
        public System.DateTime FECHA_TRANSACION { get; set; }
    }
}
