//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_ANTICIPOS_CLIENTE
    {
        public string RUC { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public System.DateTime DD_FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FEC_VCTO { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> IMPORTE_DOCUMENTO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string OBSERVACION { get; set; }
    }
}
