//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_OBTENER_VENTA_UTIL
    {
        public System.DateTime DD_FECHA_DOCU { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUMERO { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public string VENDEDOR { get; set; }
        public string CDG_PROD { get; set; }
        public string PRODUCTO { get; set; }
        public string GRUPO { get; set; }
        public string SUB_GRUPO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_UNIT { get; set; }
        public Nullable<decimal> TOTAL_VENTA { get; set; }
        public Nullable<decimal> TOTAL_VENTA_SIN_IGV { get; set; }
        public Nullable<decimal> COSTO_UNIT { get; set; }
        public Nullable<decimal> COSTO_TOTAL { get; set; }
        public Nullable<decimal> UTILIDAD_BRUTA_SIN_IGV { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string ALMACEN { get; set; }
    }
}
