//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_PRODUCTO
    {
        public string TIPO_PRODUCTO { get; set; }
        public string CATEGORIA { get; set; }
        public string GRUPO { get; set; }
        public string SUBGRUPO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string INVENTARIABLE { get; set; }
        public string UNIDAD_COMPRA { get; set; }
        public string UNIDAD_ALMACEN { get; set; }
        public string UNIDAD_VENTA { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<decimal> ANCHO { get; set; }
        public Nullable<decimal> LARGO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> DD_FECHA_ULTIMA_MODIFICACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
    }
}
