//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VWUTIL_ALMACEN
    {
        public decimal ID_DOCUMENTO { get; set; }
        public System.DateTime DD_FECHA_MOVIMIENTO { get; set; }
        public string FECHA_MOVIMIENTO { get; set; }
        public string MOVIMIENTO_ALMACEN { get; set; }
        public string TDOC { get; set; }
        public string RUC { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public string NUM_DOCU { get; set; }
        public string MONEDA { get; set; }
        public string CODIGO_PRODUCTO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string PRODUCTO { get; set; }
        public string CANTIDAD_COMPRA { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO_SOLES { get; set; }
        public string UNIDAD_COMPRA_PRODUCTO { get; set; }
        public string UNIDAD_ALMACEN { get; set; }
        public string UNIDAD_ALMACEN_PRODUCTO { get; set; }
        public Nullable<decimal> FACTOR_PRODUCTO { get; set; }
        public Nullable<decimal> FACTOR_ALMACEN { get; set; }
    }
}
