//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_SERVICIO_OTS
    {
        public System.DateTime DD_FECHA_REGISTRO { get; set; }
        public string TIPO_SERV { get; set; }
        public string REFERENCIA2 { get; set; }
        public string CODACT { get; set; }
        public string CUADRILLA { get; set; }
        public Nullable<decimal> VALOR_PUNTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> TOTAL_VALOR_PUNTO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string COD_REF { get; set; }
        public string NOMBRE { get; set; }
    }
}
