//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_LETRA_CLIENTE
    {
        public string NRO_CANJE { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NRO_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_GIRO { get; set; }
        public System.DateTime DD_VENCIMIENTO { get; set; }
        public string ACEPTANTE { get; set; }
        public string SECCION { get; set; }
        public string MONEDA { get; set; }
        public decimal IMPORTE { get; set; }
        public int PLAZO { get; set; }
        public string FACTURAS { get; set; }
        public string NRO_BANCO { get; set; }
        public string REFERENCIA { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
        public string RUC_AVAL { get; set; }
        public string NOMBRE_AVAL { get; set; }
        public string DIRECCION_AVAL { get; set; }
        public string TELEFONO_AVAL { get; set; }
        public string ESTADO { get; set; }
    }
}
