//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_COSTO_VALORVENTA
    {
        public string TP { get; set; }
        public string CODIGO_CAJERO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string TIPO { get; set; }
        public string MESANO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string MON { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> TOTAL_VENTA { get; set; }
        public Nullable<decimal> COSTO_UNITARIO { get; set; }
        public Nullable<decimal> COSTO_TOTAL { get; set; }
        public Nullable<decimal> UTILIDAD { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public string TD { get; set; }
    }
}
