//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_ENTREGA_RENDIR
    {
        public string TIPO_ANALITICA { get; set; }
        public string ANALITICA { get; set; }
        public string NUM_CAJA { get; set; }
        public string FORMA_PAGO { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
        public string MONEDA { get; set; }
        public System.DateTime DD_FECHA_CAJA { get; set; }
        public string NUMERO { get; set; }
        public string MOVIMIENTO { get; set; }
        public decimal IMPORTE { get; set; }
        public Nullable<System.DateTime> FEC_CIERRE { get; set; }
        public string OBSERVACION { get; set; }
        public string CDG_OP { get; set; }
        public string CDG_OS { get; set; }
    }
}
