//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_CONSUMO_COMENSAL2
    {
        public string LOCAL { get; set; }
        public string REF1 { get; set; }
        public string AREA { get; set; }
        public string TIPO_TRABAJADOR { get; set; }
        public string COD_CC { get; set; }
        public string CODIGO_CC { get; set; }
        public string NOMBRE_CC { get; set; }
        public string CODIGO { get; set; }
        public string RUC { get; set; }
        public string COMENSAL { get; set; }
        public string TIPO_MENU { get; set; }
        public string NOMBRE { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime DD_FECHA_REGISTRO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string CDG_TT { get; set; }
    }
}
