//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_REQ_OC_CC
    {
        public System.DateTime DD_FECHA_OC { get; set; }
        public string NUMERO_PEDIDO { get; set; }
        public string CLIENTE { get; set; }
        public string MON_OP { get; set; }
        public Nullable<decimal> TOTAL_OP { get; set; }
        public string SUCURSAL { get; set; }
        public string ORDEN_COMPRA { get; set; }
        public string PROVEEDOR { get; set; }
        public string MON_OC { get; set; }
        public decimal TOTAL_OC { get; set; }
        public string RESPONSABLE { get; set; }
        public string NRO_CHEQUE { get; set; }
        public string ING_ALMACEN { get; set; }
        public string ESTADO_OC { get; set; }
    }
}
