//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VWUTIL_COMPRAS
    {
        public string TDOC { get; set; }
        public string PROVEEDOR { get; set; }
        public string RUC { get; set; }
        public System.DateTime DD_FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_PERIODO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string CORRELATIVO { get; set; }
        public string NUM_DOCU { get; set; }
        public string MONEDA { get; set; }
        public string CODIGO_PRODUCTO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string PRODUCTO { get; set; }
        public string UNIDAD_COMPRA_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string UNIDAD_COMPRA_DOCUMENTO { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public Nullable<decimal> IMPORTE_SOLES { get; set; }
        public string NUM_GUIA { get; set; }
        public Nullable<int> AÑO_PERIODO { get; set; }
        public Nullable<int> MES_PERIODO { get; set; }
    }
}
