//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_LETRA_CLIENTE2
    {
        public string RUC { get; set; }
        public string NOMBRE { get; set; }
        public string DISTRITO { get; set; }
        public string TELEFONO { get; set; }
        public string GARANTE { get; set; }
        public string TELEFONO_GARANTE { get; set; }
        public string CONTRATO { get; set; }
        public string LETRA { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public Nullable<int> DIAS_VENCIDOS { get; set; }
        public string ESTADO { get; set; }
    }
}
