//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_GASTOS_COMPRAS
    {
        public int ID_DOCUMENTO { get; set; }
        public decimal NUM_SEC { get; set; }
        public decimal ID_PERSONA { get; set; }
        public System.DateTime DD_FECHA_EMISION { get; set; }
        public Nullable<System.DateTime> FEC_CMP { get; set; }
        public string NUM { get; set; }
        public string RUC_PRV { get; set; }
        public string NUM_DOCU { get; set; }
        public string TDOC { get; set; }
        public string PROVEEDOR { get; set; }
        public string MON { get; set; }
        public decimal TOTAL { get; set; }
        public string GLOSA { get; set; }
        public string CDG_GASTO { get; set; }
        public string NOMBRE_GASTO { get; set; }
        public string CUENTA_REFERENCIA_GASTO { get; set; }
        public string CDG_CC { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string CUENTA { get; set; }
        public string NOMBRE_CUENTA { get; set; }
    }
}
