//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_DOCUMENTO_COMPRA_PERCEPCION
    {
        public string RUC_PRV { get; set; }
        public string PROVEEDOR { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUM_DOCU { get; set; }
        public System.DateTime DD_FECHA_DOCUMENTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_CONTABILIZACION { get; set; }
        public string NUMERO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_COMPROBANTE { get; set; }
        public string NUMERO_COMPROBANTE { get; set; }
        public Nullable<decimal> IMPORTE_PERCEPCION { get; set; }
        public string OBSERVACION { get; set; }
    }
}
