//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_STOCK_UBICACION
    {
        public string CODIGO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string NOMBRE { get; set; }
        public decimal UBICACION_01 { get; set; }
        public decimal UBICACION_02 { get; set; }
        public decimal UBICACION_03 { get; set; }
        public decimal UBICACION_04 { get; set; }
        public decimal STOCK_ACTUAL { get; set; }
        public Nullable<decimal> TOTAL_STOCK_UBICACION { get; set; }
        public Nullable<decimal> DIFERENCIA { get; set; }
        public Nullable<System.DateTime> DD_FECHA_ACTUAL { get; set; }
    }
}
