//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_VENTA_EXPORTAR
    {
        public System.DateTime DD_FECHA_EMISION { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
        public string CODIGO_EMPRESA { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public string DIRECCION { get; set; }
        public string MONEDA { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string VENDEDOR { get; set; }
        public string REFTDOC { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string NUMERO_MAQUINA { get; set; }
        public string TEXTO_IMPORTE { get; set; }
        public decimal SUB_TOTAL { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public decimal POR_IGV { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public decimal IGV { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string CATEGORIA { get; set; }
        public string PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string UNIDAD { get; set; }
        public decimal PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> PRECIO_ORIGINAL { get; set; }
        public decimal SUB_TOTALITEM { get; set; }
        public Nullable<decimal> IGVITEM { get; set; }
        public Nullable<decimal> POR_IGVITEM { get; set; }
        public string SWT_PIGV { get; set; }
        public string TIPO { get; set; }
        public string TIPO_AFEC_IGV { get; set; }
        public decimal EFECTIVO { get; set; }
        public decimal ABONO { get; set; }
        public decimal VUELTO { get; set; }
        public string TURNO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public int SECUENCIA { get; set; }
    }
}
