//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_VALORIZACION_PROD
    {
        public string ALMACEN_NOMBRE { get; set; }
        public string CDG_PROD { get; set; }
        public string CDG_BARRA { get; set; }
        public string NOM_PROD { get; set; }
        public string TIPO_GUIA { get; set; }
        public Nullable<decimal> COSTO_TOTAL_SOLES { get; set; }
        public Nullable<decimal> COSTO_TOTAL_DOLARES { get; set; }
    }
}
