//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_PRODUCTO2
    {
        public Nullable<System.DateTime> DD_FECHA_HOY { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string CATEGORIA { get; set; }
        public string GRUPO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string PRODUCTO { get; set; }
        public decimal ALMACEN1 { get; set; }
        public decimal ALMACEN2 { get; set; }
        public Nullable<decimal> STOCK_ACTUAL { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> PRECIO_MINIMO { get; set; }
        public Nullable<decimal> FACTOR_CONVERSION { get; set; }
    }
}
