//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_DAOT_VENTA
    {
        public System.DateTime DD_FECHA_DOCU { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUMERO { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> MONTO_DOLAR { get; set; }
        public Nullable<decimal> TC { get; set; }
    }
}
