//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_PAGO_CONSUMO_COMENSAL
    {
        public string RUC { get; set; }
        public string COMENSAL { get; set; }
        public System.DateTime DD_FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_PAGO { get; set; }
        public string TIPO_MENU { get; set; }
        public decimal MONTO_TRABAJADOR { get; set; }
        public decimal MONTO_EMPRESA { get; set; }
        public Nullable<decimal> IMPORTE_PAGADO { get; set; }
    }
}
