//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_DOCUMENTO_VENTA
    {
        public System.DateTime ANO { get; set; }
        public System.DateTime MES { get; set; }
        public System.DateTime DD_FECHA_DOCUMENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string NROOP { get; set; }
        public System.DateTime DD_FECHA_VENCIMIENTO { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public string VENDEDOR { get; set; }
        public string FORMA_PAGO { get; set; }
        public string CODIGO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string NOMBRE { get; set; }
        public string MONEDA { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO { get; set; }
        public decimal VALOR_VENTA { get; set; }
        public Nullable<decimal> MONTO_DOC { get; set; }
        public Nullable<decimal> TIPO_CAMBIO_DOC { get; set; }
        public Nullable<decimal> BASE_CALCULADA { get; set; }
        public Nullable<decimal> COSTO_ESTANDAR_SOLES { get; set; }
        public Nullable<decimal> MARGEN_BRUTO_SOLES { get; set; }
        public Nullable<decimal> PORCENTAJE_MARGEN { get; set; }
        public string ALMACEN { get; set; }
    }
}
