//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_SALDO_KARDEX
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string INVENTARIABLE { get; set; }
        public string ALMACEN { get; set; }
        public string USUARIO_PROCESO_ULTIMA_VALORIZACION { get; set; }
        public System.DateTime FECHA_PROCESO_ULTIMA_VALORIZACION { get; set; }
        public decimal AñO { get; set; }
        public decimal MES { get; set; }
        public decimal SALDO_MES { get; set; }
        public Nullable<System.DateTime> DD_FECHA_FIN_MES { get; set; }
    }
}
