//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_ATENCION_TICKET
    {
        public string NUM_TICKET { get; set; }
        public string PERSONA { get; set; }
        public System.DateTime DD_FECHA_EMISION { get; set; }
        public Nullable<System.DateTime> DD_DFECHA_ATENCION { get; set; }
        public int CANTIDAD { get; set; }
        public string NOMBRE { get; set; }
    }
}
