//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_COMPROMISO_FINANCIERO
    {
        public string REFERENCIA { get; set; }
        public string COMPROMISO { get; set; }
        public string num_comp { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
        public string NUM_COR { get; set; }
        public string MONEDA { get; set; }
        public Nullable<System.DateTime> DD_FECHA_DESEMBOLSO { get; set; }
        public Nullable<System.DateTime> DD_FECHA_VENCIMIENTO { get; set; }
        public string num_itm { get; set; }
        public string FECHA_DOCU { get; set; }
        public string FECHA_VENC_DOCU { get; set; }
        public string TDOC { get; set; }
        public string num_docu { get; set; }
        public Nullable<decimal> CUOTA { get; set; }
        public Nullable<decimal> PAGO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
    }
}
