//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_PAGO_PROVEEDOR
    {
        public System.DateTime DD_FECHA_EMISION { get; set; }
        public string RUC { get; set; }
        public string PROVEEDOR { get; set; }
        public string NOMBRE_CONTACTO1 { get; set; }
        public string TELEFONO_CONTACTO1 { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
        public string CUENTA_CCI { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string CONTADO_CREDITO { get; set; }
        public string TDOC { get; set; }
        public string NUM_DOCU { get; set; }
        public string MON { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
    }
}
