//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_ORDEN_PEDIDO_LETRA
    {
        public string NUMERO_PEDIDO { get; set; }
        public System.DateTime DD_FECHA_PEDIDO { get; set; }
        public string CODIGO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string NOMBRE { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public decimal IMPORTE { get; set; }
        public string LETRAS { get; set; }
    }
}
