//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_OBTENER_REGISTRO_VENTA
    {
        public decimal NUM_OPERACION { get; set; }
        public System.DateTime DD_FECHA_DOCU { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUMERO { get; set; }
        public string RUC { get; set; }
        public string CLIENTE { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string CATEGORIA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string GRUPO { get; set; }
        public string SUB_GRUPO { get; set; }
        public string CONDICION_PAGO { get; set; }
        public string CODIGO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string CODIGO_PEDIDO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> PRECIO_LISTA { get; set; }
        public Nullable<decimal> POR_DSCTO { get; set; }
        public Nullable<decimal> IMPORTE_DSCTO { get; set; }
        public Nullable<decimal> PRECIO_CON_DSCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> IMPORTE_ITEM { get; set; }
        public Nullable<decimal> IMPORTE_ITEM_CON_DSCTO { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public decimal IGV { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> MONTO_DOLAR { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string REFERENCIA { get; set; }
        public string ALMACEN { get; set; }
        public string TIPO_REGISTRO { get; set; }
    }
}
