//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_REQ_OP_COB
    {
        public System.DateTime DD_FECHA_OP { get; set; }
        public string NUMERO_PEDIDO { get; set; }
        public string CLIENTE { get; set; }
        public string MON_OP { get; set; }
        public decimal TOTAL_OP { get; set; }
        public string SUCURSAL { get; set; }
        public string VENDEDOR { get; set; }
        public string ESTADO { get; set; }
        public Nullable<decimal> TOTAL_OC { get; set; }
        public string RESPONSABLE { get; set; }
        public Nullable<decimal> TOTAL_CHEQUE { get; set; }
        public Nullable<decimal> TOTAL_GCC { get; set; }
        public Nullable<decimal> TOTAL_COBRADO { get; set; }
        public Nullable<decimal> TOTAL_X_COBRAR { get; set; }
        public string USUARIO_CREACION { get; set; }
    }
}
