//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_VW_ASIGNACION_ACTIVO_FIJO
    {
        public string ACTIVO_FIJO { get; set; }
        public string SERIE { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string CLASE { get; set; }
        public string NIVEL_OBS { get; set; }
        public string USO { get; set; }
        public string ESTADO_FISICO { get; set; }
        public string CLIENTE { get; set; }
        public string DD_FECHA_RETORNO { get; set; }
        public string DD_FECHA_INICIO { get; set; }
        public string OBSERVACION { get; set; }
    }
}
