//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQ_ALMACEN
    {
        public string req_id { get; set; }
        public decimal cooc_id { get; set; }
        public decimal ID_GUIA { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal cantidad { get; set; }
        public decimal secuencia_req { get; set; }
        public decimal secuencia_oc { get; set; }
        public decimal secuencia_guia { get; set; }
    }
}
