//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_CAPACITACION
    {
        public string CODIGO { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string TIPO_EVENTO { get; set; }
        public string TIPO_CURSO { get; set; }
        public string TIPO_ORGANIZACION { get; set; }
        public string ORGANIZACION { get; set; }
        public string NOMBRE_CURSO { get; set; }
        public System.DateTime FECHA_IREALIZACION { get; set; }
        public System.DateTime FECHA_FREALIZACION { get; set; }
        public decimal CANTIDAD_HORA { get; set; }
        public string LUGAR { get; set; }
        public string NOTA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
