//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RRHH_PLANILLA()
        {
            this.RRHH_DETALLE_PLANILLA = new HashSet<RRHH_DETALLE_PLANILLA>();
        }
    
        public decimal ID_PERSONA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public int SEMANA { get; set; }
        public string NUMERO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string AREA { get; set; }
        public string CARGO { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string OBRA { get; set; }
        public string CDG_PLANILLA { get; set; }
        public string CDG_MON { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<decimal> IMP_REMUNERATIVO { get; set; }
        public Nullable<decimal> IMP_NOREMUNERATIVO { get; set; }
        public Nullable<decimal> IMP_INGRESO { get; set; }
        public Nullable<decimal> IMP_DESCUENTO { get; set; }
        public Nullable<decimal> IMP_APORTACION { get; set; }
        public Nullable<decimal> IMP_NETO { get; set; }
        public System.DateTime FECHA_PROCESO { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_CESE { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_VACA { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_VACA { get; set; }
        public string REGIMEN_PENSIONARIO { get; set; }
        public string CUSPP { get; set; }
        public string ESTABLE_CONTRATADO { get; set; }
        public string SWT_PAGO { get; set; }
        public string ANO_REF1 { get; set; }
        public string CDG_PROY { get; set; }
        public string NUM_VOUC { get; set; }
        public string NUM_ORIG { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_S { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_S { get; set; }
        public string NUM_CTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRHH_DETALLE_PLANILLA> RRHH_DETALLE_PLANILLA { get; set; }
    }
}
