//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_CONSOLIDADO_ASISTENCIA
    {
        public int ID_PERSONA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public int SEMANA { get; set; }
        public string CDG_PROY { get; set; }
        public int DIAS_TRAB { get; set; }
        public Nullable<int> FALTAS { get; set; }
        public decimal HORA_TRAB { get; set; }
        public decimal MINU_TARD { get; set; }
        public Nullable<decimal> HE_25 { get; set; }
        public decimal HE_35 { get; set; }
        public Nullable<decimal> HE_60 { get; set; }
        public decimal HE_100 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<decimal> FERIADO { get; set; }
    }
}
