//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_VIGENCIA_REINTEGRO
    {
        public string CDG_PARA { get; set; }
        public string TIPO_OBRERO { get; set; }
        public decimal VALOR { get; set; }
        public string UNIDAD { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public string ANOI { get; set; }
        public int MESI { get; set; }
        public string ANOF { get; set; }
        public int MESF { get; set; }
        public string CDG_PARA_APLICA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
