//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_CONTROL_VACACION
    {
        public decimal ID_CONTROL { get; set; }
        public int ID_PERSONA { get; set; }
        public string TIPO_VACA { get; set; }
        public string ANO { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public System.DateTime FECHA_RETORNO { get; set; }
        public decimal DIAS_EFECTIVO { get; set; }
        public decimal DIAS_VACA { get; set; }
        public string COMENTARIO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> ANO_PAGO { get; set; }
        public Nullable<int> MES_PAGO { get; set; }
        public Nullable<int> SEMANA { get; set; }
        public string CDG_PROY { get; set; }
    }
}
