//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_MARCACION_ASISTENCIA
    {
        public decimal ID_MARCACION { get; set; }
        public int ID_PERSONA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public System.DateTime INGRESO { get; set; }
        public string HORA_INGRESO { get; set; }
        public System.DateTime SALIDA { get; set; }
        public string HORA_SALIDA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public int SEMANA { get; set; }
        public string CDG_PROY { get; set; }
        public string RUTA { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public Nullable<int> FALTAS { get; set; }
        public decimal HORA_TRAB { get; set; }
        public decimal MINU_TARD { get; set; }
        public Nullable<decimal> HE_25 { get; set; }
        public decimal HE_35 { get; set; }
        public Nullable<decimal> HE_60 { get; set; }
        public decimal HE_100 { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
