//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_REFERENCIA_CUENTA
    {
        public decimal ID_PERSONA { get; set; }
        public string BANCO { get; set; }
        public string NUM_CTA { get; set; }
        public string MONEDA { get; set; }
        public string TIPO_CTA { get; set; }
        public decimal SECUENCIA { get; set; }
        public string ACTIVO { get; set; }
    }
}
