//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_DERECHO_HABIENTE
    {
        public decimal ID_PERSONA { get; set; }
        public decimal ID_DH { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string NRO_DOCUMENTO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string SEXO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string ESTADO { get; set; }
        public string VINCULO_FAMILIAR { get; set; }
        public string INCAPACIDAD { get; set; }
        public string RESOLUCION_DIRECTORAL { get; set; }
        public string DOMICILIO_DH { get; set; }
        public string SITUACION_DH { get; set; }
        public string ALTA_DH { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string MOTIVO_BAJA { get; set; }
        public string BAJA_DH { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public string TD_ACREDITA_PATERNIDAD { get; set; }
        public string NRO_ACREDITA_PATERNIDAD { get; set; }
        public string VIA { get; set; }
        public string ZONA { get; set; }
        public string NOMBRE_VIA { get; set; }
        public string NOMBRE_ZONA { get; set; }
        public string NRO_VIA { get; set; }
        public string INTERIOR { get; set; }
        public string REFERENCIA { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string UBIGEO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
