//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_PRESTAMO
    {
        public string CODIGO { get; set; }
        public string CDG_PARA { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public decimal INTERES { get; set; }
        public string MONEDA { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string COMENTARIO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
