//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_DETALLE_PLANILLA
    {
        public string CDG_PARAM { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string CDG_PLANILLA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public int SEMANA { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal SECUENCIA { get; set; }
        public string IDA { get; set; }
        public string NRNR { get; set; }
        public string AFECTO_ESSALUD { get; set; }
        public string AFECTO_ESSALUD_SCTR { get; set; }
        public string AFECTO_SENATI { get; set; }
        public string AFECTO_SISTEMA_PENSION { get; set; }
        public string AFECTO_SISTEMA_PRIVADO_PENSION { get; set; }
        public string AFECTO_QUINTA_CATEGORIA { get; set; }
        public string AFECTO_GRATIFICACION { get; set; }
        public string AFECTO_CTS { get; set; }
        public string AFECTO_VACACION { get; set; }
        public string AFECTO_UTIL { get; set; }
        public string AFECTO_LIQUIDACION { get; set; }
        public string TIPO_ASISTENCIA { get; set; }
        public string ASISTENCIA { get; set; }
        public string SWT_PLA { get; set; }
        public string NOMBRE_PARAM { get; set; }
        public string REFE_PARAM { get; set; }
        public string UNIDAD { get; set; }
        public string AFECTO_ONP_SCTR { get; set; }
        public string AFECTO_CONAFOVICER { get; set; }
        public Nullable<decimal> ANO_REF1 { get; set; }
        public Nullable<decimal> MES_REF1 { get; set; }
        public Nullable<decimal> SEMANA_REF1 { get; set; }
        public string CDG_PROY { get; set; }
    
        public virtual RRHH_PLANILLA RRHH_PLANILLA { get; set; }
    }
}
