//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_CTA_5TA_CAT
    {
        public string CDG_PARA { get; set; }
        public int ID_PERSONA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public decimal IMPORTE { get; set; }
        public string TIPO { get; set; }
        public string SWT_TIPO { get; set; }
    }
}
