//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRHH_DISTRIBUCION_CENTROCOSTO
    {
        public decimal ID_PERSONA { get; set; }
        public string ANO { get; set; }
        public int MES { get; set; }
        public int SEMANA { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string CODIGO_ESTABLECIMIENTO { get; set; }
        public decimal PORCENTAJE { get; set; }
        public decimal NUM_HORA { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_CREACION { get; set; }
    }
}
