//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_TAREO
    {
        public string ANO { get; set; }
        public decimal MES { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal ID_PERSONA { get; set; }
        public string CDG_CC { get; set; }
        public string SCDG_CC { get; set; }
        public string CDG_TURNO { get; set; }
        public string TIPO_DIA { get; set; }
        public Nullable<decimal> DIA { get; set; }
        public Nullable<decimal> HORA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
