//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_ACTIVIDAD_PROYECTO
    {
        public decimal ID_PROYECTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public decimal ID_ACTIVIDAD { get; set; }
        public string NOMBRE_ACTIVIDAD { get; set; }
        public string OBSERVACION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> VV_UNIT { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public Nullable<decimal> HORA_ESTIMADA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> TC { get; set; }
    }
}
