//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_TAREA_PROYECTO
    {
        public decimal ID_PROYECTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string DESCRIPCION_TAREA { get; set; }
        public string COMENTARIO { get; set; }
        public string ESTADO { get; set; }
        public string ESTADO_APROBACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
    }
}
