//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_SERVICIO_TECNICO_IMAGEN
    {
        public string NUMERO_FRE { get; set; }
        public string SERIE_GENERADA { get; set; }
        public string NOMBRE_IMAGEN { get; set; }
        public string TITULO { get; set; }
        public byte[] IMG_IMAGEN { get; set; }
        public int SECUENCIA { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
