//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_TRANSPORTE_PROYECTO
    {
        public decimal ID_PROYECTO { get; set; }
        public decimal SECUENCIA { get; set; }
        public string CHOFER { get; set; }
        public string LICENCIA { get; set; }
        public string VEHICULO { get; set; }
        public string PLACA { get; set; }
        public string CERTIFICADO { get; set; }
        public decimal KILOMETRAJE { get; set; }
        public string DEPARTAMENTO_DE { get; set; }
        public string PROVINCIA_DE { get; set; }
        public string DISTRITO_DE { get; set; }
        public string DEPARTAMENTO_HASTA { get; set; }
        public string PROVINCIA_HASTA { get; set; }
        public string DISTRITO_HASTA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
