//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SI_INDICADOR
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CATEGORIA { get; set; }
        public string TIPO_INDICADOR { get; set; }
        public string DEFINICION { get; set; }
        public string OBJETIVO { get; set; }
        public string PROCEDIMIENTO_CALCULO { get; set; }
        public string FORMULA { get; set; }
        public string VISTA { get; set; }
        public string ORIGEN_DB { get; set; }
        public decimal META { get; set; }
        public decimal PRECAUCION_DE { get; set; }
        public decimal PRECAUCION_HASTA { get; set; }
        public decimal CRITICO { get; set; }
        public string UNIDAD { get; set; }
        public string FRECUENCIA { get; set; }
        public string RESPONSABLE { get; set; }
        public string ABREVIATURA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
