//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_acceso_opcion
    {
        public string codi_grup_usua { get; set; }
        public string codi_empr { get; set; }
        public int codi_opcion { get; set; }
        public bool flag_nuevo { get; set; }
        public bool flag_modi { get; set; }
        public bool flag_anul { get; set; }
        public bool flag_elim { get; set; }
        public bool flag_print { get; set; }
        public bool flag_busc { get; set; }
        public string usua_crea { get; set; }
        public System.DateTime fech_crea { get; set; }
        public string usua_modi { get; set; }
        public Nullable<System.DateTime> fech_modi { get; set; }
    }
}
