//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_campo_documento
    {
        public string codi_empr { get; set; }
        public string tipo_docu { get; set; }
        public string codi_campo { get; set; }
        public int secuencia { get; set; }
        public string nomb_campo { get; set; }
        public bool flag_cab_det { get; set; }
        public bool flag_alfa_nume { get; set; }
        public bool flag_obli { get; set; }
        public Nullable<int> cant_deci { get; set; }
        public string desc_campo { get; set; }
        public int long_campo { get; set; }
        public string usua_crea { get; set; }
        public System.DateTime fech_crea { get; set; }
        public string usua_modi { get; set; }
        public Nullable<System.DateTime> fech_modi { get; set; }
        public string estado { get; set; }
    }
}
