//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catalogo
    {
        public string codi_cata { get; set; }
        public string campo_ubl { get; set; }
        public string desc_cata { get; set; }
        public string orig_cata { get; set; }
        public string usua_crea { get; set; }
        public System.DateTime fech_crea { get; set; }
        public string usua_modi { get; set; }
        public Nullable<System.DateTime> fech_modi { get; set; }
        public string estado { get; set; }
    }
}
