//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catalogo_detalle
    {
        public string codi_cata { get; set; }
        public string codi_cata_deta { get; set; }
        public string desc_cata_deta { get; set; }
        public string codi_equi { get; set; }
    }
}
