//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public string codi_empr { get; set; }
        public string ruc_empr { get; set; }
        public string razo_soci { get; set; }
        public string nomb_come { get; set; }
        public string ubigeo { get; set; }
        public string dire_empr { get; set; }
        public string urba_empr { get; set; }
        public string prov_empr { get; set; }
        public string dpto_empr { get; set; }
        public string dist_empr { get; set; }
        public string fono1 { get; set; }
        public string fono2 { get; set; }
        public string fax_empr { get; set; }
        public string correo_empr { get; set; }
        public string repr_lega { get; set; }
        public string dni_repr_lega { get; set; }
        public byte[] logo_empr { get; set; }
        public string nomb_logo { get; set; }
        public string usuario_sol { get; set; }
        public string clave_sol { get; set; }
        public byte[] firma_digi { get; set; }
        public string nomb_firm { get; set; }
        public string clave_firma { get; set; }
        public string serv_smtp { get; set; }
        public Nullable<int> ancho { get; set; }
        public Nullable<int> alto { get; set; }
        public string resolucion { get; set; }
        public string ruta_archivo { get; set; }
        public string web_empr { get; set; }
        public string usua_crea { get; set; }
        public Nullable<System.DateTime> fech_crea { get; set; }
        public string usua_modi { get; set; }
        public Nullable<System.DateTime> fech_modi { get; set; }
        public string estado { get; set; }
        public string puerto { get; set; }
        public string correofe { get; set; }
        public string pass_corr { get; set; }
        public string cc_correo { get; set; }
        public Nullable<decimal> ssl { get; set; }
    }
}
