//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pass_cliente
    {
        public string codi_empr { get; set; }
        public string tipo_docu { get; set; }
        public string nume_docu { get; set; }
        public byte[] pass_clie { get; set; }
    }
}
