//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTIL_MP
    {
        public string CDG_TABLA { get; set; }
        public string NUMERO { get; set; }
        public string CODIGO_SUCURSAL { get; set; }
        public string CDG_MOVI { get; set; }
        public string TIPO_IS { get; set; }
        public string ESTADO { get; set; }
        public string MOTIVO_MP { get; set; }
        public Nullable<decimal> PROB_CIERRE { get; set; }
        public string TIPO_UTIL { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    }
}
