//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FAEL_BOLETA_V03
    {
        public System.DateTime FECH_DOCU { get; set; }
        public string CONF_RAZON_SOCIAL { get; set; }
        public string NOMB_COMERCIAL { get; set; }
        public string UBIGEO { get; set; }
        public string CONF_DIRECCION { get; set; }
        public string URBANIZACION { get; set; }
        public string PROVINCIA { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string DISTRITO { get; set; }
        public string PAIS { get; set; }
        public string CONF_RUC { get; set; }
        public string TIPO_DOCU_EMPR { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
        public string CLIENTE_RUC { get; set; }
        public string TIPO_DOCU_CLIE { get; set; }
        public string CLIENTE_NOMBRE { get; set; }
        public string UNIDAD { get; set; }
        public decimal DVEDV_CANTIDAD { get; set; }
        public string EXISTENCIA_NOMBRE { get; set; }
        public Nullable<double> VALO_UNIT { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string TIPO_PRECIO { get; set; }
        public Nullable<double> IGV_ITEM { get; set; }
        public Nullable<double> IGV_ITEM_2 { get; set; }
        public string AFEC_IGV { get; set; }
        public string CODI_IGV { get; set; }
        public string NOMB_IGV { get; set; }
        public string NOMB_IGV_INT { get; set; }
        public string TOTA_OPER_GRAV_TIPO { get; set; }
        public Nullable<double> VALO_VENT_GRAV_TOTA { get; set; }
        public string TOTA_OPER_INAF_TIPO { get; set; }
        public decimal VALO_VENT_INAF_TOTA { get; set; }
        public string TOTA_OPER_EXON_TIPO { get; set; }
        public decimal VALO_VENT_EXON_TOTA { get; set; }
        public Nullable<double> VALO_VENT_ITEM { get; set; }
        public decimal VEDV_MONTO_IGV { get; set; }
        public decimal VEDV_MONTO_IGV_2 { get; set; }
        public string CODI_IGV_TOTA { get; set; }
        public string NOMB_IGV_TOTA { get; set; }
        public string NOMB_IGV_INT_TOTA { get; set; }
        public string CODI_DCTO { get; set; }
        public Nullable<decimal> VEDV_MONTO_DESCUENTO { get; set; }
        public Nullable<decimal> VEDV_MONTO { get; set; }
        public string MONEDA { get; set; }
        public string GUIAS { get; set; }
        public string TIPO_GUIA { get; set; }
        public string TIPO_LEYENDA_MONTO { get; set; }
        public string LEYENDA_MONTO { get; set; }
        public int DVEDV_SECUENCIA { get; set; }
        public string EXISTENCIA_CODACTUAL { get; set; }
        public Nullable<decimal> VALO_NO_ONER_ITEM { get; set; }
        public string TIPO_VALO_NO_ONER_ITEM { get; set; }
        public string VERSION_UBL { get; set; }
        public string VERSION_ESTRUCTURA { get; set; }
        public string TOTA_OPER_GRAT_TIPO { get; set; }
        public int VALO_VENT_GRAT_TOTA { get; set; }
        public string TIPO_DOCU_ANTICIPO { get; set; }
        public string ANTICIPOS { get; set; }
        public string ANTICIPO_RUC { get; set; }
        public string TIPO_DOCU_RUC_ANTICIPO { get; set; }
        public decimal TOTAL_ANTICIPO { get; set; }
        public string TIPO_OPER { get; set; }
        public string VENDEDOR { get; set; }
        public string ORDEN_COMPRA { get; set; }
        public string PEDIDO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string VEDV_GLOSA { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public string CLIENTE_UBIGEO { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string FONO_CLIENTE { get; set; }
        public string TIPO_LEYENDA_TTG { get; set; }
        public string LEYENDA_TTG { get; set; }
        public string USUARIO { get; set; }
        public string HORA_EMISION { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public string CODI_INTE { get; set; }
        public Nullable<decimal> PORCENTAJE_IGV { get; set; }
        public Nullable<decimal> VALOR_INAFECTO_ITEM { get; set; }
        public Nullable<decimal> ICBPER { get; set; }
        public Nullable<decimal> ICBPER_TOTAL { get; set; }
    }
}
