//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FAEL_BAJA_V01
    {
        public string CONF_RAZON_SOCIAL { get; set; }
        public string CONF_RUC { get; set; }
        public string TIPO_DOCU_EMPR { get; set; }
        public System.DateTime FECH_DOCU { get; set; }
        public string TIPO_DOCU_DOCU { get; set; }
        public string SERIE { get; set; }
        public Nullable<decimal> CORRELATIVO { get; set; }
        public string MOTIVO { get; set; }
        public int NUME_ITEM { get; set; }
        public string ID_BAJA { get; set; }
        public string FECH_GENE { get; set; }
        public string VERSION_UBL { get; set; }
        public string VERSION_ESTRUCTURA { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
    }
}
