//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace US_EXCHANGER.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FAEL_RESUMEN_V02
    {
        public string CONF_RAZON_SOCIAL { get; set; }
        public string CONF_RUC { get; set; }
        public string TIPO_DOCU_EMPR { get; set; }
        public System.DateTime FECH_DOCU { get; set; }
        public string TIPO_DOCU_DOCU { get; set; }
        public string MONEDA { get; set; }
        public string SERIE { get; set; }
        public string ID_TIPO_IDENTIDAD { get; set; }
        public string NUMERO_IDENTIDAD { get; set; }
        public Nullable<decimal> INICIO_RANGO { get; set; }
        public Nullable<decimal> FIN_RANGO { get; set; }
        public string TOTA_OPER_GRAV_TIPO { get; set; }
        public decimal VALO_VENT_GRAV_TOTA { get; set; }
        public string TOTA_OPER_INAF_TIPO { get; set; }
        public decimal VALO_VENT_INAF_TOTA { get; set; }
        public string TOTA_OPER_EXON_TIPO { get; set; }
        public decimal VALO_VENT_EXON_TOTA { get; set; }
        public int INDICADOR_SUM_OTRO_CARGO { get; set; }
        public int TOTAL_SUM_OTRO_CARGO { get; set; }
        public int TOTAL_ISC { get; set; }
        public int TOTAL_ISC_2 { get; set; }
        public string CODI_ISC { get; set; }
        public string NOMB_ISC { get; set; }
        public string CODI_INTE_ISC { get; set; }
        public decimal VEDV_MONTO_IGV { get; set; }
        public decimal VEDV_MONTO_IGV_2 { get; set; }
        public string CODI_IGV_TOTA { get; set; }
        public string NOMB_IGV_TOTA { get; set; }
        public string NOMB_IGV_INT_TOTA { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public int NUME_ITEM { get; set; }
        public string FECH_GENE { get; set; }
        public string VERSION_UBL { get; set; }
        public string VERSION_ESTRUCTURA { get; set; }
        public string ID_RESUMEN { get; set; }
        public string TIPO_DOCU { get; set; }
        public string NUME_DOCU { get; set; }
        public int CODIGO_OPERACION { get; set; }
        public string TIPO_DOCU_REF { get; set; }
        public string NUME_DOCU_REF { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
    }
}
