SELECT D."NOMBRE" "Moneda", D."REFERENCIA1" "Simbolo" , CREATEDATE "Fecha", TP."PRECIO_COMPRA" "Compra", TP."PRECIO_VENTA" "Venta", D."Numero", TC."Nombre" AS "Tipo Persona"  FROM DIVI_TIPO_CAMBIO TP

LEFT JOIN "OPE_DETALLE_TABLA" D ON TP."COD_MONEDA_CAMBIO" = D."NUMERO" AND D.CODIGO='MONEDA' 
LEFT JOIN "OPE_DETALLE_TABLA" TC ON TC."NUMERO" = TP."COD_TIPO_CAMBIO" AND TC.CODIGO='TCAM_DIVI'

WHERE  CREATEDATE = (SELECT FORMAT (getdate(), 'yyyy-MM-dd') )