
SELECT D."NOMBRE" "Moneda", D."REFERENCIA1" "Simbolo" , FORMAT(CREATEDATE, 'dd/MM/yyyy') "Fecha", TP."PRECIO_COMPRA" "Compra", TP."PRECIO_VENTA" "Venta",  TC."Nombre" AS "Tipo Persona"  FROM DIVI_TIPO_CAMBIO TP

LEFT JOIN "OPE_DETALLE_TABLA" D ON TP."COD_MONEDA_CAMBIO" = D."NUMERO" 
LEFT JOIN "OPE_DETALLE_TABLA" TC ON TC."NUMERO" = TP."COD_TIPO_CAMBIO" AND TC.CODIGO='TCAM_DIVI'
WHERE 
D.CODIGO='MONEDA' AND TP."fecha" BETWEEN '[US_FECHA_DESDE]' AND '[US_FECHA_HASTA]'
