SELECT D."NOMBRE" "Moneda", D."REFERENCIA1" "Simbolo" , CREATEDATE "Fecha", TP."PRECIO_COMPRA" "Compra", TP."PRECIO_VENTA" "Venta", D."Numero"  FROM DIVI_TIPO_CAMBIO TP

LEFT JOIN "OPE_DETALLE_TABLA" D ON TP."COD_MONEDA_CAMBIO" = D."NUMERO" WHERE D.CODIGO='MONEDA' 


AND CREATEDATE = (SELECT FORMAT (getdate(), 'yyyy-MM-dd') )