SELECT D."NOMBRE" "Moneda", D."REFERENCIA1" "Simbolo" , FORMAT(fecha, 'dd/MM/yyyy') "Fecha", TP."PRECIO_COMPRA" "Compra", TP."PRECIO_VENTA" "Venta"  FROM "OPE_TIPOCAMBIO_DIVISA" TP

LEFT JOIN "OPE_DETALLE_TABLA" D ON TP."COD_MONEDA_CAMBIO" = D."NUMERO" 
WHERE 
D.CODIGO='MONEDA' 
AND D."NUMERO" = '[US_COD_MONEDA]'

AND TP."fecha" BETWEEN '[US_FECHA_DESDE]' AND '[US_FECHA_DESDE]'
